import { notFound, redirect } from "next/navigation";
import { Box, CalendarCheck, Factory, Gauge, MapPin, ShieldCheck, Wrench } from "lucide-react";
import { db } from "../../../lib/db";
import { assetStatusLabel, criticalityLabel } from "../../../modules/assets/asset-service";
import { formatThaiDate } from "../../../lib/date-time/bangkok-time";

export const dynamic = "force-dynamic";

export default async function PublicAssetPage({ params }: { params: Promise<{token:string}> }) {
  const {token}=await params;
  const asset=await db.asset.findUnique({where:{publicToken:token},include:{plant:true,family:true,assetClass:true,assetType:true,zone:true,parent:true,children:{where:{registrationStatus:"ACTIVE"},include:{assetType:true,technicalValues:{include:{field:true},orderBy:{sortOrder:"asc"}},cmWorks:{where:{status:"CLOSED"},orderBy:{closedAt:"desc"},take:1},documents:{where:{status:"ACTIVE",publicVisible:true},orderBy:{createdAt:"desc"}}},orderBy:{componentCode:"asc"}},technicalValues:{include:{field:true},orderBy:{sortOrder:"asc"}},cmWorks:{where:{status:"CLOSED"},orderBy:{closedAt:"desc"},take:1},documents:{where:{status:"ACTIVE",publicVisible:true},orderBy:{createdAt:"desc"}}}}); if(!asset||asset.registrationStatus!=="ACTIVE")notFound(); if(asset.parent)redirect(`/asset-qr/${asset.parent.publicToken}`);
  const defaults=await db.assetQrSetting.findUnique({where:{plantId:asset.plantId}}); const setting={showLocation:true,showManufacturer:true,showModel:true,showSerialNumber:false,showTechnical:false,showLastCmDate:true,showLastCmTitle:false,showLastCmOutcome:false,...defaults,...safeJson(asset.qrOverrideJson)}; const cm=asset.cmWorks[0];
  return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between gap-4 px-4 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-600 text-white"><Wrench size={20}/></span><div><p className="font-black">PowerCare Assets</p><p className="text-xs text-slate-500">{asset.plant.name}</p></div></div><span className="flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700"><ShieldCheck size={14}/>Read only</span></div></header>
    <div className="mx-auto max-w-4xl px-4 py-6 sm:py-10"><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="bg-gradient-to-br from-slate-900 to-slate-700 px-5 py-7 text-white sm:px-8"><p className="font-mono text-sm font-bold text-emerald-300">{asset.code}</p><h1 className="mt-2 text-3xl font-black">{asset.nameEn||asset.nameTh}</h1><p className="mt-1 text-slate-300">{asset.nameEn&&asset.nameTh!==asset.nameEn?asset.nameTh:asset.family.nameEn||""}</p><div className="mt-5 flex flex-wrap gap-2"><Pill>{assetStatusLabel(asset.operatingStatus)}</Pill><Pill>{criticalityLabel(asset.criticality)}</Pill><Pill>{asset.assetType?.nameTh||"ชุดเครื่องจักร"}</Pill></div></div>
      {setting.showImage&&asset.imageStoragePath?<img src={`/asset-images/${asset.id}?token=${asset.publicToken}`} alt={`รูป ${asset.nameTh}`} className="aspect-[16/8] w-full object-cover"/>:null}<div className="grid gap-0 md:grid-cols-2"><PublicSection icon={Factory} title="ข้อมูลเครื่องจักร"><Rows items={[["Asset Class",asset.assetClass.nameTh],["Asset Family",`${asset.family.code} · ${asset.family.nameTh}`],["ผู้ผลิต",setting.showManufacturer?asset.manufacturer:null],["รุ่น",setting.showModel?asset.model:null],["Serial Number",setting.showSerialNumber?asset.serialNumber:null]].filter(([,v])=>v) as string[][]}/></PublicSection>{setting.showLocation?<PublicSection icon={MapPin} title="ตำแหน่งติดตั้ง"><Rows items={[["Site",`${asset.plant.code} · ${asset.plant.name}`],["Zone",asset.zone?.name||"ไม่ระบุ"],["ตำแหน่ง",asset.installationLocation||"ไม่ระบุ"]]}/></PublicSection>:null}</div>
    </section>
    {asset.children.length?<section className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Box size={20}/></span><div><h2 className="text-lg font-black">อุปกรณ์ภายใต้เครื่องแม่</h2><p className="text-sm text-slate-500">{asset.children.length} รายการ</p></div></div><div className="mt-4 grid gap-4">{asset.children.map(child=><article key={child.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-sm font-black text-emerald-700">{child.code}</p><h3 className="mt-1 text-lg font-black">{child.nameEn||child.nameTh}</h3><p className="text-sm text-slate-500">{child.assetType?.code||child.componentCode} · {child.assetType?.nameTh||"อุปกรณ์ย่อย"}</p></div><div className="flex gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{assetStatusLabel(child.operatingStatus)}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{criticalityLabel(child.criticality)}</span></div></div><Rows items={[["ผู้ผลิต",setting.showManufacturer?child.manufacturer:null],["รุ่น",setting.showModel?child.model:null],["Serial Number",setting.showSerialNumber?child.serialNumber:null],["ตำแหน่ง",setting.showLocation?child.installationLocation:null]].filter(([,value])=>value) as string[][]}/>{setting.showTechnical&&child.technicalValues.length?<div className="mt-3 grid gap-2 sm:grid-cols-2">{child.technicalValues.map(value=><div key={value.id} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">{value.field?.labelTh||value.customLabel}</p><p className="mt-1 font-black">{value.value||"-"} <span className="text-xs text-slate-500">{value.unit||value.field?.unit}</span></p></div>)}</div>:null}{setting.showLastCmDate?<p className="mt-3 text-sm text-slate-600"><strong>ซ่อมล่าสุด:</strong> {child.cmWorks[0]?.closedAt?date(child.cmWorks[0].closedAt):"ยังไม่มีประวัติ"}</p>:null}{child.documents.length?<div className="mt-3 flex flex-wrap gap-2">{child.documents.map(doc=><a key={doc.id} href={`/asset-files/${doc.id}`} className="rounded-lg bg-slate-50 px-3 py-2 text-sm font-bold text-emerald-700">{doc.title}</a>)}</div>:null}</article>)}</div></section>:null}
    <section className="mt-5 grid gap-4 sm:grid-cols-2"><Summary icon={Wrench} title="ซ่อมล่าสุด" value={setting.showLastCmDate?(cm?.closedAt?date(cm.closedAt):"ยังไม่มีประวัติ"):"ไม่เปิดเผย"} detail={setting.showLastCmTitle?cm?.problemTitle:null}/><Summary icon={CalendarCheck} title="PM ล่าสุด" value="ยังไม่มีข้อมูล" detail="เตรียมพร้อมสำหรับระบบ PM"/></section>
    {setting.showTechnical&&asset.technicalValues.length?<section className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Gauge size={20}/></span><h2 className="text-lg font-black">ข้อมูลทางเทคนิค</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{asset.technicalValues.map(value=><div key={value.id} className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">{value.field?.labelTh||value.customLabel}</p><p className="mt-1 text-lg font-black">{value.value||"-"} <span className="text-sm font-medium text-slate-500">{value.unit||value.field?.unit}</span></p></div>)}</div></section>:null}{asset.documents.length?<section className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-black">เอกสารที่เปิดเผย</h2><div className="mt-3 grid gap-2">{asset.documents.map(doc=><a key={doc.id} href={`/asset-files/${doc.id}`} className="rounded-xl bg-slate-50 px-4 py-3 font-bold text-emerald-700">{doc.title} · Rev {doc.revision||"-"}</a>)}</div></section>:null}
    <p className="mt-6 text-center text-xs text-slate-500">ข้อมูลสำหรับการตรวจสอบหน้างาน · กรุณาติดต่อแผนกซ่อมบำรุงหากพบความผิดปกติ</p></div></main>
}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold ring-1 ring-white/20">{children}</span>}
function PublicSection({icon:Icon,title,children}:{icon:typeof Box;title:string;children:React.ReactNode}){return <section className="border-b border-slate-200 p-5 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0 sm:p-7"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon size={20}/></span><h2 className="font-black">{title}</h2></div><div className="mt-4">{children}</div></section>}
function Rows({items}:{items:string[][]}){return <dl className="grid gap-3">{items.map(([label,value])=><div key={label} className="flex justify-between gap-4 border-b border-slate-100 pb-2 text-sm"><dt className="text-slate-500">{label}</dt><dd className="text-right font-bold">{value}</dd></div>)}</dl>}
function Summary({icon:Icon,title,value,detail}:{icon:typeof Wrench;title:string;value:string;detail?:string|null}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon size={20}/></span><div><p className="text-xs font-bold text-slate-500">{title}</p><p className="font-black">{value}</p></div></div>{detail?<p className="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-sm font-semibold">{detail}</p>:null}</section>}
function date(value:Date){return formatThaiDate(value,"long")}
function safeJson(value:string|null){try{return value?JSON.parse(value):{}}catch{return {}}}
