import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "../../../../components/app-shell";
import { PmWorkAssignmentForm } from "../../../../components/pm/pm-work-assignment-form";
import { PmWorkResultForm } from "../../../../components/pm/pm-work-result-form";
import { requireUser } from "../../../../lib/session";
import { canExecutePmWork, canManagePmPlans, canViewPm } from "../../../../modules/auth/permission";
import { canUseUserPermission, PermissionKey } from "../../../../modules/auth/site-admin-permissions";
import { createCmFromAbnormalPm, listPmCmOptions } from "../../../../modules/pm/pm-cm-service";
import { resolvePmPageScope } from "../../../../modules/pm/pm-page-scope";
import { assignPmWork, cancelPmWork, claimPmWork, completePmWork, correctCompletedPmWorkResult, getPmWorkDetail, listEligiblePmAssignees, startPmWork } from "../../../../modules/pm/pm-work-service";

type Query = { organizationId?: string; plantId?: string; saved?: string; error?: string };
export default async function PmWorkDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Query> }) {
  const user = await requireUser(); if (!canViewPm(user)) redirect("/dashboardcm");
  const query = await searchParams; const scope = await resolvePmPageScope(user, query); const serviceScope = { organizationId: scope.organization.id, plantId: scope.plant.id }; const { id: workId } = await params;
  const work = await getPmWorkDetail(user, { ...serviceScope, workId }); const manager = canManagePmPlans(user); const executor = canExecutePmWork(user); const performer = work.assignees.some(a => a.userId === user.id); const users = manager ? await listEligiblePmAssignees(user, serviceScope) : [];
  const canCreateCm = canUseUserPermission(user, PermissionKey.CREATE_INTERNAL_REQUEST); const cmOptions = work.status === "COMPLETED" && work.result === "ABNORMAL" && !work.originatingCmWork && canCreateCm ? await listPmCmOptions(user, serviceScope) : null;
  async function assign(data: FormData) { "use server"; const actor = await requireUser(); try { await assignPmWork(actor, { ...serviceScope, workId, leadUserId: String(data.get("leadUserId") ?? ""), collaboratorUserIds: data.getAll("collaboratorUserIds").map(String) }); } catch (e) { redirect(workUrl(workId, serviceScope, { error: message(e) })); } redirect(workUrl(workId, serviceScope, { saved: "assigned" })); }
  async function claim() { "use server"; const actor = await requireUser(); try { await claimPmWork(actor, { ...serviceScope, workId }); } catch (e) { redirect(workUrl(workId, serviceScope, { error: message(e) })); } redirect(workUrl(workId, serviceScope, { saved: "claimed" })); }
  async function start() { "use server"; const actor = await requireUser(); try { await startPmWork(actor, { ...serviceScope, workId }); } catch (e) { redirect(workUrl(workId, serviceScope, { error: message(e) })); } redirect(workUrl(workId, serviceScope, { saved: "started" })); }
  async function complete(data: FormData) { "use server"; const actor = await requireUser(); try { await completePmWork(actor, { ...serviceScope, workId, result: String(data.get("result") ?? ""), note: String(data.get("note") ?? "") }); } catch (e) { redirect(workUrl(workId, serviceScope, { error: message(e) })); } redirect(workUrl(workId, serviceScope, { saved: "completed" })); }
  async function cancel(data: FormData) { "use server"; const actor = await requireUser(); try { await cancelPmWork(actor, { ...serviceScope, workId, reason: String(data.get("reason") ?? "") }); } catch (e) { redirect(workUrl(workId, serviceScope, { error: message(e) })); } redirect(workUrl(workId, serviceScope, { saved: "canceled" })); }
  async function correct(data: FormData) { "use server"; const actor = await requireUser(); try { await correctCompletedPmWorkResult(actor, { ...serviceScope, workId, result: String(data.get("result") ?? ""), note: String(data.get("note") ?? ""), reason: String(data.get("reason") ?? "") }); } catch (e) { redirect(workUrl(workId, serviceScope, { error: message(e) })); } redirect(workUrl(workId, serviceScope, { saved: "corrected" })); }
  async function createCm(data: FormData) { "use server"; const actor = await requireUser(); try { await createCmFromAbnormalPm(actor, { ...serviceScope, workId, pmWorkUpdatedAt: work.updatedAt, categoryId: String(data.get("categoryId") ?? ""), zoneId: String(data.get("zoneId") ?? "") }); } catch (e) { redirect(workUrl(workId, serviceScope, { error: message(e) })); } redirect(workUrl(workId, serviceScope, { saved: "cm-created" })); }
  return <AppShell><main className="mx-auto grid max-w-4xl gap-5"><Link className="font-bold text-[var(--primary)]" href={`/dashboardpm/work?${new URLSearchParams(serviceScope)}`}>← PM Work</Link>
    {query.saved ? <p className="rounded-2xl bg-emerald-500/10 p-4 text-sm font-bold text-emerald-700" role="status">PM work updated.</p> : null}{query.error ? <p className="rounded-2xl bg-red-500/10 p-4 text-sm font-bold text-red-700" role="alert">{query.error}</p> : null}
    <section className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6 shadow-[var(--shadow)]"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-bold text-[var(--primary)]">{work.number}</p><h1 className="mt-1 text-3xl font-extrabold">{work.assetCodeSnapshot ?? "—"} · {work.assetNameSnapshot}</h1></div><span className="h-fit rounded-full bg-[var(--soft)] px-3 py-1 text-sm font-bold">{work.status}</span></div><p className="mt-3 text-sm text-[var(--muted)]">Planned {work.pmPlan.plannedDateKey}{work.overdue ? " · Overdue" : ""}</p>{work.retiredAsset ? <p className="mt-3 rounded-xl bg-amber-500/10 p-3 text-sm font-bold text-amber-700" role="alert">Asset registration is inactive. Confirmed work remains until explicitly completed or canceled.</p> : null}<h2 className="mt-5 font-extrabold">Team</h2><ul className="mt-2 text-sm">{work.assignees.map(a => <li key={a.id}>{a.role}: {a.user.fullName}</li>)}{!work.assignees.length ? <li>Unassigned</li> : null}</ul>{work.result ? <p className="mt-4 rounded-xl bg-[var(--soft)] p-3"><strong>Result: {work.result}</strong>{work.resultNote ? <><br />{work.resultNote}</> : null}</p> : null}</section>
    {manager && !["COMPLETED", "CANCELED"].includes(work.status) ? <PmWorkAssignmentForm action={assign} users={users} defaultLeadId={work.assignees.find(a => a.role === "LEAD")?.userId} defaultCollaboratorIds={work.assignees.filter(a => a.role === "COLLABORATOR").map(a => a.userId)} /> : null}
    {executor && work.status === "PLANNED" && !work.assignees.length ? <form action={claim}><button className="min-h-11 rounded-xl bg-[var(--primary)] px-4 font-bold text-white">Claim work</button></form> : null}{executor && performer && work.status === "PLANNED" ? <form action={start}><button className="min-h-11 rounded-xl bg-[var(--primary)] px-4 font-bold text-white">Start PM</button></form> : null}{executor && performer && work.status === "IN_PROGRESS" ? <PmWorkResultForm action={complete} /> : null}{manager && work.status === "COMPLETED" ? <PmWorkResultForm action={correct} correction defaultResult={work.result ?? "NORMAL"} defaultNote={work.resultNote ?? ""} /> : null}
    {work.originatingCmWork ? <section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-4"><p className="font-bold">งาน CM ที่เชื่อมโยง</p><Link className="mt-2 inline-flex min-h-11 items-center font-bold text-emerald-700 underline" href={`/work/${work.originatingCmWork.id}`}>{work.originatingCmWork.number} · {work.originatingCmWork.status}</Link></section> : null}
    {cmOptions ? <form action={createCm} className="grid gap-3 rounded-2xl border border-amber-500/30 bg-amber-500/5 p-4"><div><h2 className="font-extrabold">สร้างงาน CM จากผล PM</h2><p className="mt-1 text-sm text-[var(--muted)]">Asset: {work.assetCodeSnapshot ?? "—"} · {work.assetNameSnapshot}<br/>อาการผิดปกติ: {work.resultNote}</p></div><label className="grid gap-1 text-sm font-bold">Category<select required name="categoryId" defaultValue="" className="min-h-11 rounded-xl border bg-[var(--surface)] px-3"><option value="" disabled>เลือก Category</option>{cmOptions.categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1 text-sm font-bold">Zone<select required name="zoneId" defaultValue="" className="min-h-11 rounded-xl border bg-[var(--surface)] px-3"><option value="" disabled>เลือก Zone</option>{cmOptions.zones.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="min-h-11 rounded-xl bg-amber-600 px-4 font-bold text-white sm:justify-self-end">สร้างงาน CM</button></form> : null}
    {(manager || (executor && performer)) && ["PLANNED", "IN_PROGRESS"].includes(work.status) ? <form action={cancel} className="grid gap-2 rounded-2xl border border-red-500/30 p-4"><label className="grid gap-1 text-sm font-bold">Cancellation reason<input className="min-h-11 rounded-xl border px-3" name="reason" required /></label><button className="min-h-11 rounded-xl border border-red-500/40 px-4 font-bold text-red-700 sm:justify-self-end">Cancel PM work</button></form> : null}
  </main></AppShell>;
}
function message(error: unknown) { return error instanceof Error ? error.message : "Unable to update PM work"; }
function workUrl(workId: string, scope: { organizationId: string; plantId: string }, value: Record<string, string>) { return `/dashboardpm/work/${workId}?${new URLSearchParams({ ...scope, ...value })}`; }
