import { redirect } from "next/navigation";
import { Eye, QrCode, Save, ShieldCheck } from "lucide-react";
import { AppShell } from "../../../components/app-shell";
import { AdminScopeHiddenFields, AdminSiteScopeSelector } from "../../../components/admin-site-scope-selector";
import { db } from "../../../lib/db";
import { requireUser } from "../../../lib/session";
import { adminScopeSearchFromFormData } from "../../../modules/admin/admin-site-scope";
import { resolveAssetScope } from "../../../modules/assets/asset-scope";
import { canManageAssetQrProfile } from "../../../modules/auth/permission";
const keys=["showImage","showLocation","showManufacturer","showModel","showSerialNumber","showTechnical","showLastCmDate","showLastCmTitle","showLastCmOutcome","showLastPmDate","showLastPmTitle","showLastPmOutcome"] as const;
async function save(formData:FormData){"use server";const user=await requireUser();if(!canManageAssetQrProfile(user))redirect("/assets");const scope=await resolveAssetScope(user,adminScopeSearchFromFormData(formData));const data=Object.fromEntries(keys.map(key=>[key,formData.get(key)==="on"]));await db.assetQrSetting.upsert({where:{plantId:scope.plant.id},create:{plantId:scope.plant.id,...data},update:data});redirect(`/assets/qr-settings?organizationId=${scope.organization.id}&plantId=${scope.plant.id}&saved=1`)}
export default async function QrSettings({searchParams}:{searchParams:Promise<{organizationId?:string;plantId?:string;saved?:string}>}){const user=await requireUser();if(!canManageAssetQrProfile(user))redirect("/assets");const query=await searchParams;const scope=await resolveAssetScope(user,query);const current=await db.assetQrSetting.findUnique({where:{plantId:scope.plant.id}});const value=(key:typeof keys[number])=>current?current[key]:["showImage","showLocation","showManufacturer","showModel","showLastCmDate","showLastPmDate"].includes(key);return <AppShell><header><p className="text-sm font-bold uppercase tracking-[.18em] text-emerald-600">Public access</p><h1 className="mt-2 text-3xl font-black">QR Public Profile</h1><p className="mt-2 text-sm text-[var(--muted)]">กำหนดข้อมูลเริ่มต้นที่ผู้สแกน QR เห็นโดยไม่ต้อง Login</p></header><div className="mt-6"><AdminSiteScopeSelector scope={scope} title="QR setting scope" description="แต่ละ Site กำหนดข้อมูลสาธารณะได้ต่างกัน"/></div>{query.saved?<p className="mt-4 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm font-bold text-emerald-700">บันทึกการตั้งค่า QR แล้ว</p>:null}<form action={save} className="mt-5 grid gap-5"><AdminScopeHiddenFields scope={scope}/><SettingGroup icon={Eye} title="ข้อมูลประจำเครื่อง"><Toggle name="showImage" label="รูปประจำเครื่อง" checked={value("showImage")}/><Toggle name="showLocation" label="Zone และตำแหน่งติดตั้ง" checked={value("showLocation")}/><Toggle name="showManufacturer" label="ผู้ผลิต" checked={value("showManufacturer")}/><Toggle name="showModel" label="รุ่น" checked={value("showModel")}/><Toggle name="showSerialNumber" label="Serial Number" checked={value("showSerialNumber")}/><Toggle name="showTechnical" label="ข้อมูลทางเทคนิคทั้งหมด" checked={value("showTechnical")}/></SettingGroup><div className="grid gap-5 lg:grid-cols-2"><SettingGroup icon={QrCode} title="CM ล่าสุด"><Toggle name="showLastCmDate" label="วันที่ซ่อมล่าสุด" checked={value("showLastCmDate")}/><Toggle name="showLastCmTitle" label="หัวข้องานซ่อมล่าสุด" checked={value("showLastCmTitle")}/><Toggle name="showLastCmOutcome" label="ผลลัพธ์ล่าสุด" checked={value("showLastCmOutcome")}/></SettingGroup><SettingGroup icon={ShieldCheck} title="PM ล่าสุด"><Toggle name="showLastPmDate" label="วันที่ PM ล่าสุด" checked={value("showLastPmDate")}/><Toggle name="showLastPmTitle" label="หัวข้อ PM ล่าสุด" checked={value("showLastPmTitle")}/><Toggle name="showLastPmOutcome" label="ผลตรวจล่าสุด" checked={value("showLastPmOutcome")}/></SettingGroup></div><button className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-5 font-bold text-white hover:bg-emerald-700 sm:justify-self-end"><Save size={18}/>บันทึกการตั้งค่า</button></form></AppShell>}
function SettingGroup({icon:Icon,title,children}:{icon:typeof Eye;title:string;children:React.ReactNode}){return <fieldset className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-sm"><legend className="sr-only">{title}</legend><div className="mb-3 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-600"><Icon size={20}/></span><h2 className="text-lg font-black">{title}</h2></div><div className="grid gap-2">{children}</div></fieldset>}
function Toggle({name,label,checked}:{name:string;label:string;checked:boolean}){return <label className="flex min-h-12 cursor-pointer items-center justify-between gap-4 rounded-xl bg-[var(--soft)] px-4 text-sm font-bold"><span>{label}</span><input type="checkbox" name={name} defaultChecked={checked} className="h-5 w-5 accent-emerald-600"/></label>}
