import { isSiteAdminRole, RoleName } from "../cm-work/cm-work-types";

export const PublicRoleName = {
  PUBLIC_REQUESTER: "PUBLIC_REQUESTER",
} as const;

export type PermissionRole = RoleName | (typeof PublicRoleName)[keyof typeof PublicRoleName];

export const PermissionKey = {
  LOGIN: "login",
  ACCESS_PUBLIC_QR: "access_public_qr",
  VIEW_DASHBOARD: "view_dashboard",
  SELECT_PLANT_CONTEXT: "select_plant_context",
  VIEW_ALL_WORK: "view_all_work",
  VIEW_PROFILE: "view_profile",
  UPDATE_OWN_PROFILE: "update_own_profile",
  VIEW_ADMIN_SETTINGS_MENU: "view_admin_settings_menu",
  MANAGE_SYSTEM_SETTINGS: "manage_system_settings",
  MANAGE_ORGANIZATION: "manage_organization",
  CREATE_INTERNAL_REQUEST: "create_internal_request",
  CREATE_PUBLIC_REQUEST: "create_public_request",
  TRACK_WORK: "track_work",
  VIEW_WORK_DETAIL: "view_work_detail",
  UPDATE_REQUEST_BEFORE_CLAIM: "update_request_before_claim",
  ATTACH_WORK_FILES: "attach_work_files",
  UPDATE_PRIORITY: "update_priority",
  UPDATE_WORK_ZONE: "update_work_zone",
  UPDATE_WORK_CATEGORY: "update_work_category",
  DELETE_WORK: "delete_work",
  CLAIM_WORK: "claim_work",
  CLAIM_WORK_FOR_OTHER: "claim_work_for_other",
  START_WORK: "start_work",
  UPDATE_WORK_PROGRESS: "update_work_progress",
  RECORD_FIX_METHOD: "record_fix_method",
  RECORD_SPARE_PARTS: "record_spare_parts",
  ATTACH_BEFORE_AFTER_PHOTOS: "attach_before_after_photos",
  SUBMIT_WAITING_CLOSE: "submit_waiting_close",
  REOPEN_WAITING_CLOSE: "reopen_waiting_close",
  VIEW_TECHNICIAN_CLOSE_DETAIL: "view_technician_close_detail",
  ASSIGN_WORK: "assign_work",
  ASSIGN_CROSS_CATEGORY: "assign_cross_category",
  REASSIGN_WORK: "reassign_work",
  CANCEL_WORK: "cancel_work",
  RECORD_CANCEL_REASON: "record_cancel_reason",
  REVIEW_WORK: "review_work",
  CLOSE_WORK: "close_work",
  EDIT_CLOSED_WORK: "edit_closed_work",
  PRINT_COMPLETION_DOCUMENT: "print_completion_document",
  EXPORT_COMPLETION_PDF: "export_completion_pdf",
  VIEW_REPORTS: "view_reports",
  EXPORT_REPORTS: "export_reports",
  VIEW_ALL_PLANTS_KPI: "view_all_plants_kpi",
  VIEW_PLANT_KPI: "view_plant_kpi",
  VIEW_MTTR_MTBF: "view_mttr_mtbf",
  VIEW_BACKLOG_OVERDUE: "view_backlog_overdue",
  VIEW_REPORT_BY_CATEGORY: "view_report_by_category",
  VIEW_REPORT_BY_ZONE: "view_report_by_zone",
  VIEW_REPORT_BY_ASSIGNEE: "view_report_by_assignee",
  VIEW_HISTORY_AUDIT: "view_history_audit",
  VIEW_MEMBERS: "view_members",
  VIEW_MEMBER_WORKLOAD: "view_member_workload",
  VIEW_MEMBER_ACTIVE_STATUS: "view_member_active_status",
  VIEW_MEMBER_DETAIL: "view_member_detail",
  FILTER_MEMBERS: "filter_members",
  VIEW_CROSS_PLANT_MEMBERS: "view_cross_plant_members",
  MANAGE_USERS_ALL_PLANTS: "manage_users_all_plants",
  MANAGE_USERS_PLANT: "manage_users_plant",
  CREATE_USER: "create_user",
  UPDATE_USER: "update_user",
  DEACTIVATE_USER: "deactivate_user",
  DELETE_USER: "delete_user",
  RESET_USER_PASSWORD: "reset_user_password",
  ASSIGN_USER_ROLE: "assign_user_role",
  ASSIGN_USER_PLANT: "assign_user_plant",
  ASSIGN_USER_CATEGORIES: "assign_user_categories",
  MANAGE_SUPER_ADMIN: "manage_super_admin",
  MANAGE_SITE_ADMIN: "manage_site_admin",
  MANAGE_PLANT_PROFILE: "manage_plant_profile",
  MANAGE_COMPANY_ORGANIZATION: "manage_company_organization",
  MANAGE_CATEGORY: "manage_category",
  MANAGE_ZONE: "manage_zone",
  MANAGE_QR_CODE: "manage_qr_code",
  MANAGE_LINE_SETTINGS: "manage_line_settings",
  MANAGE_ENGINEER_ASSIGNMENT: "manage_engineer_assignment",
  MANAGE_SLA_DUE_DATE: "manage_sla_due_date",
  MANAGE_PRIORITY: "manage_priority",
  MANAGE_WORK_STATUS: "manage_work_status",
  VIEW_NOTIFICATIONS: "view_notifications",
  SEND_TEAM_NOTIFICATION: "send_team_notification",
  MANAGE_ANNOUNCEMENTS: "manage_announcements",
  VIEW_ANNOUNCEMENTS: "view_announcements",
  SEND_LINE_NOTIFICATION: "send_line_notification",
  TEST_LINE_MESSAGING: "test_line_messaging",
  VIEW_FEEDBACK_ALL_PLANTS: "view_feedback_all_plants",
  VIEW_FEEDBACK_PLANT: "view_feedback_plant",
  REPLY_FEEDBACK: "reply_feedback",
  EXPORT_FEEDBACK: "export_feedback",
  VIEW_AUDIT_LOG_ALL_PLANTS: "view_audit_log_all_plants",
  VIEW_AUDIT_LOG_PLANT: "view_audit_log_plant",
  MANAGE_SITE_ADMIN_PERMISSION: "manage_site_admin_permission",
  MANAGE_CHECKBOX_PERMISSION: "manage_checkbox_permission",
  VIEW_CROSS_PLANT_DATA: "view_cross_plant_data",
  EXPORT_AUDIT_LOG: "export_audit_log",
  BACKUP_RESTORE_DATA: "backup_restore_data",
  VIEW_DEVELOPER_SYSTEM_LOG: "view_developer_system_log",
  VIEW_STORE_DASHBOARD: "view_store_dashboard",
  MANAGE_STORE: "manage_store",
  MANAGE_SPARE_PARTS: "manage_spare_parts",
  VIEW_STORE_STOCK: "view_store_stock",
  RECEIVE_STOCK: "receive_stock",
  ADJUST_STOCK: "adjust_stock",
  CREATE_STORE_ISSUE: "create_store_issue",
  APPROVE_STORE_ISSUE: "approve_store_issue",
  ISSUE_STOCK: "issue_stock",
  VIEW_STORE_TRACKING: "view_store_tracking",
  VIEW_STORE_REPORTS: "view_store_reports",
  ENABLE_PUBLIC_STORE_ISSUE: "enable_public_store_issue",
  REQUIRE_PUBLIC_ISSUE_CONTACT: "require_public_issue_contact",
} as const;

export type PermissionKey = (typeof PermissionKey)[keyof typeof PermissionKey];

export type SiteAdminPermissionRecord = {
  userId: string;
  plantId: string;
  permissionKey: string;
  enabled: boolean;
};

export type PermissionUserContext = {
  id?: string;
  role: string;
  organizationId?: string | null;
  plantId?: string | null;
  siteAdminPermissions?: SiteAdminPermissionRecord[];
};

export const SITE_ADMIN_CONFIGURABLE_PERMISSIONS = [
  PermissionKey.ASSIGN_WORK,
  PermissionKey.REASSIGN_WORK,
  PermissionKey.CANCEL_WORK,
  PermissionKey.RECORD_CANCEL_REASON,
  PermissionKey.CLOSE_WORK,
  PermissionKey.EXPORT_REPORTS,
  PermissionKey.MANAGE_USERS_PLANT,
  PermissionKey.CREATE_USER,
  PermissionKey.UPDATE_USER,
  PermissionKey.DEACTIVATE_USER,
  PermissionKey.DELETE_USER,
  PermissionKey.RESET_USER_PASSWORD,
  PermissionKey.ASSIGN_USER_ROLE,
  PermissionKey.ASSIGN_USER_PLANT,
  PermissionKey.ASSIGN_USER_CATEGORIES,
  PermissionKey.MANAGE_PLANT_PROFILE,
  PermissionKey.MANAGE_CATEGORY,
  PermissionKey.MANAGE_ZONE,
  PermissionKey.MANAGE_QR_CODE,
  PermissionKey.MANAGE_LINE_SETTINGS,
  PermissionKey.MANAGE_ENGINEER_ASSIGNMENT,
  PermissionKey.MANAGE_SLA_DUE_DATE,
  PermissionKey.MANAGE_PRIORITY,
  PermissionKey.TEST_LINE_MESSAGING,
  PermissionKey.VIEW_FEEDBACK_PLANT,
  PermissionKey.REPLY_FEEDBACK,
  PermissionKey.EXPORT_FEEDBACK,
  PermissionKey.VIEW_AUDIT_LOG_PLANT,
  PermissionKey.MANAGE_STORE,
  PermissionKey.MANAGE_SPARE_PARTS,
  PermissionKey.VIEW_STORE_STOCK,
  PermissionKey.RECEIVE_STOCK,
  PermissionKey.ADJUST_STOCK,
  PermissionKey.VIEW_STORE_REPORTS,
  PermissionKey.ENABLE_PUBLIC_STORE_ISSUE,
  PermissionKey.REQUIRE_PUBLIC_ISSUE_CONTACT,
] as const satisfies readonly PermissionKey[];

export type PermissionOption = {
  key: (typeof SITE_ADMIN_CONFIGURABLE_PERMISSIONS)[number];
  label: string;
  group: string;
  description?: string;
};

export const SITE_ADMIN_PERMISSION_OPTIONS: readonly PermissionOption[] = [
  { key: PermissionKey.ASSIGN_USER_CATEGORIES, label: "กำหนด Category ให้ User", group: "User Management" },
  { key: PermissionKey.ASSIGN_WORK, label: "มอบหมายงาน", group: "Assignment / Control" },
  { key: PermissionKey.REASSIGN_WORK, label: "เปลี่ยนผู้รับผิดชอบงาน", group: "Assignment / Control" },
  { key: PermissionKey.CANCEL_WORK, label: "ยกเลิกงาน", group: "Assignment / Control" },
  { key: PermissionKey.RECORD_CANCEL_REASON, label: "ใส่เหตุผลการยกเลิกงาน", group: "Assignment / Control" },
  { key: PermissionKey.CLOSE_WORK, label: "ปิดงาน", group: "Assignment / Control" },
  { key: PermissionKey.EXPORT_REPORTS, label: "Export Reports", group: "Reports / Analytics" },
  { key: PermissionKey.MANAGE_USERS_PLANT, label: "จัดการ Users เฉพาะ Site", group: "User Management" },
  { key: PermissionKey.CREATE_USER, label: "สร้าง User ใหม่", group: "User Management" },
  { key: PermissionKey.UPDATE_USER, label: "แก้ไข User", group: "User Management" },
  { key: PermissionKey.DEACTIVATE_USER, label: "ปิดใช้งาน User", group: "User Management" },
  { key: PermissionKey.DELETE_USER, label: "ลบ User", group: "User Management" },
  { key: PermissionKey.RESET_USER_PASSWORD, label: "Reset Password / ส่ง Invite", group: "User Management" },
  { key: PermissionKey.ASSIGN_USER_ROLE, label: "กำหนด Role ให้ User", group: "User Management" },
  { key: PermissionKey.ASSIGN_USER_PLANT, label: "กำหนด Site ให้ User", group: "User Management" },
  { key: PermissionKey.MANAGE_PLANT_PROFILE, label: "จัดการ Site Profile", group: "Configuration" },
  { key: PermissionKey.MANAGE_CATEGORY, label: "จัดการ Category", group: "Configuration" },
  { key: PermissionKey.MANAGE_ZONE, label: "จัดการ Zone", group: "Configuration" },
  { key: PermissionKey.MANAGE_QR_CODE, label: "จัดการ QR Code", group: "Configuration" },
  { key: PermissionKey.MANAGE_LINE_SETTINGS, label: "จัดการ LINE Settings", group: "Configuration" },
  { key: PermissionKey.MANAGE_ENGINEER_ASSIGNMENT, label: "เปิด/ปิด Engineer Assignment", group: "Configuration" },
  { key: PermissionKey.MANAGE_SLA_DUE_DATE, label: "ตั้งค่า SLA / Due Date", group: "Configuration" },
  { key: PermissionKey.MANAGE_PRIORITY, label: "ตั้งค่า Priority", group: "Configuration" },
  { key: PermissionKey.TEST_LINE_MESSAGING, label: "ทดสอบ LINE Messaging", group: "Communication" },
  { key: PermissionKey.VIEW_FEEDBACK_PLANT, label: "ดู Feedback เฉพาะ Site", group: "Feedback" },
  { key: PermissionKey.REPLY_FEEDBACK, label: "ตอบกลับ Feedback", group: "Feedback" },
  { key: PermissionKey.EXPORT_FEEDBACK, label: "Export Feedback", group: "Feedback" },
  { key: PermissionKey.VIEW_AUDIT_LOG_PLANT, label: "ดู Audit Log เฉพาะ Site", group: "Security / Audit" },
  { key: PermissionKey.MANAGE_STORE, label: "Manage Store", group: "Store" },
  { key: PermissionKey.MANAGE_SPARE_PARTS, label: "Manage Spare Parts", group: "Store" },
  { key: PermissionKey.VIEW_STORE_STOCK, label: "View Store Stock", group: "Store" },
  { key: PermissionKey.RECEIVE_STOCK, label: "Receive Stock", group: "Store" },
  { key: PermissionKey.ADJUST_STOCK, label: "Adjust Stock", group: "Store" },
  { key: PermissionKey.VIEW_STORE_REPORTS, label: "View Store Reports", group: "Store" },
  { key: PermissionKey.ENABLE_PUBLIC_STORE_ISSUE, label: "Enable Public Store Issue", group: "Store" },
  { key: PermissionKey.REQUIRE_PUBLIC_ISSUE_CONTACT, label: "Require Public Issue Contact", group: "Store" },
];

export const ENGINEER_CONFIGURABLE_PERMISSIONS = [
  PermissionKey.ASSIGN_WORK,
  PermissionKey.REASSIGN_WORK,
  PermissionKey.SEND_TEAM_NOTIFICATION,
] as const satisfies readonly PermissionKey[];

const alwaysAllowedByRole: Record<PermissionRole, ReadonlySet<PermissionKey>> = {
  [RoleName.ADMIN]: new Set(Object.values(PermissionKey)),
  [RoleName.ORGANIZATION_ADMIN]: new Set([
    PermissionKey.LOGIN,
    PermissionKey.VIEW_DASHBOARD,
    PermissionKey.SELECT_PLANT_CONTEXT,
    PermissionKey.VIEW_ALL_WORK,
    PermissionKey.VIEW_PROFILE,
    PermissionKey.UPDATE_OWN_PROFILE,
    PermissionKey.VIEW_ADMIN_SETTINGS_MENU,
    PermissionKey.MANAGE_ORGANIZATION,
    PermissionKey.MANAGE_COMPANY_ORGANIZATION,
    PermissionKey.MANAGE_PLANT_PROFILE,
    PermissionKey.CREATE_INTERNAL_REQUEST,
    PermissionKey.TRACK_WORK,
    PermissionKey.VIEW_WORK_DETAIL,
    PermissionKey.UPDATE_REQUEST_BEFORE_CLAIM,
    PermissionKey.ATTACH_WORK_FILES,
    PermissionKey.UPDATE_PRIORITY,
    PermissionKey.UPDATE_WORK_ZONE,
    PermissionKey.UPDATE_WORK_CATEGORY,
    PermissionKey.CLAIM_WORK,
    PermissionKey.CLAIM_WORK_FOR_OTHER,
    PermissionKey.ASSIGN_WORK,
    PermissionKey.ASSIGN_CROSS_CATEGORY,
    PermissionKey.REASSIGN_WORK,
    PermissionKey.CANCEL_WORK,
    PermissionKey.RECORD_CANCEL_REASON,
    PermissionKey.REVIEW_WORK,
    PermissionKey.CLOSE_WORK,
    PermissionKey.PRINT_COMPLETION_DOCUMENT,
    PermissionKey.EXPORT_COMPLETION_PDF,
    PermissionKey.VIEW_REPORTS,
    PermissionKey.EXPORT_REPORTS,
    PermissionKey.VIEW_ALL_PLANTS_KPI,
    PermissionKey.VIEW_PLANT_KPI,
    PermissionKey.VIEW_MTTR_MTBF,
    PermissionKey.VIEW_BACKLOG_OVERDUE,
    PermissionKey.VIEW_REPORT_BY_CATEGORY,
    PermissionKey.VIEW_REPORT_BY_ZONE,
    PermissionKey.VIEW_REPORT_BY_ASSIGNEE,
    PermissionKey.VIEW_HISTORY_AUDIT,
    PermissionKey.VIEW_MEMBERS,
    PermissionKey.VIEW_MEMBER_WORKLOAD,
    PermissionKey.VIEW_MEMBER_ACTIVE_STATUS,
    PermissionKey.VIEW_MEMBER_DETAIL,
    PermissionKey.FILTER_MEMBERS,
    PermissionKey.VIEW_CROSS_PLANT_MEMBERS,
    PermissionKey.MANAGE_USERS_ALL_PLANTS,
    PermissionKey.MANAGE_USERS_PLANT,
    PermissionKey.CREATE_USER,
    PermissionKey.UPDATE_USER,
    PermissionKey.DEACTIVATE_USER,
    PermissionKey.DELETE_USER,
    PermissionKey.RESET_USER_PASSWORD,
    PermissionKey.ASSIGN_USER_ROLE,
    PermissionKey.ASSIGN_USER_PLANT,
    PermissionKey.ASSIGN_USER_CATEGORIES,
    PermissionKey.MANAGE_SITE_ADMIN,
    PermissionKey.MANAGE_CATEGORY,
    PermissionKey.MANAGE_ZONE,
    PermissionKey.MANAGE_QR_CODE,
    PermissionKey.MANAGE_LINE_SETTINGS,
    PermissionKey.MANAGE_ENGINEER_ASSIGNMENT,
    PermissionKey.MANAGE_SLA_DUE_DATE,
    PermissionKey.MANAGE_PRIORITY,
    PermissionKey.VIEW_NOTIFICATIONS,
    PermissionKey.SEND_TEAM_NOTIFICATION,
    PermissionKey.VIEW_ANNOUNCEMENTS,
    PermissionKey.SEND_LINE_NOTIFICATION,
    PermissionKey.TEST_LINE_MESSAGING,
    PermissionKey.VIEW_FEEDBACK_PLANT,
    PermissionKey.REPLY_FEEDBACK,
    PermissionKey.EXPORT_FEEDBACK,
    PermissionKey.VIEW_AUDIT_LOG_PLANT,
    PermissionKey.MANAGE_CHECKBOX_PERMISSION,
    PermissionKey.VIEW_CROSS_PLANT_DATA,
    PermissionKey.EXPORT_AUDIT_LOG,
    PermissionKey.VIEW_STORE_DASHBOARD,
    PermissionKey.VIEW_STORE_STOCK,
    PermissionKey.VIEW_STORE_REPORTS,
  ]),
  [RoleName.SITE_ADMIN]: new Set([
    PermissionKey.LOGIN,
    PermissionKey.VIEW_DASHBOARD,
    PermissionKey.VIEW_ALL_WORK,
    PermissionKey.VIEW_PROFILE,
    PermissionKey.UPDATE_OWN_PROFILE,
    PermissionKey.VIEW_ADMIN_SETTINGS_MENU,
    PermissionKey.MANAGE_PLANT_PROFILE,
    PermissionKey.CREATE_INTERNAL_REQUEST,
    PermissionKey.TRACK_WORK,
    PermissionKey.VIEW_WORK_DETAIL,
    PermissionKey.UPDATE_REQUEST_BEFORE_CLAIM,
    PermissionKey.ATTACH_WORK_FILES,
    PermissionKey.UPDATE_PRIORITY,
    PermissionKey.UPDATE_WORK_ZONE,
    PermissionKey.UPDATE_WORK_CATEGORY,
    PermissionKey.CLAIM_WORK,
    PermissionKey.CLAIM_WORK_FOR_OTHER,
    PermissionKey.START_WORK,
    PermissionKey.UPDATE_WORK_PROGRESS,
    PermissionKey.RECORD_FIX_METHOD,
    PermissionKey.RECORD_SPARE_PARTS,
    PermissionKey.SUBMIT_WAITING_CLOSE,
    PermissionKey.REOPEN_WAITING_CLOSE,
    PermissionKey.VIEW_TECHNICIAN_CLOSE_DETAIL,
    PermissionKey.ASSIGN_CROSS_CATEGORY,
    PermissionKey.REVIEW_WORK,
    PermissionKey.PRINT_COMPLETION_DOCUMENT,
    PermissionKey.EXPORT_COMPLETION_PDF,
    PermissionKey.VIEW_REPORTS,
    PermissionKey.VIEW_PLANT_KPI,
    PermissionKey.VIEW_MTTR_MTBF,
    PermissionKey.VIEW_BACKLOG_OVERDUE,
    PermissionKey.VIEW_REPORT_BY_CATEGORY,
    PermissionKey.VIEW_REPORT_BY_ZONE,
    PermissionKey.VIEW_REPORT_BY_ASSIGNEE,
    PermissionKey.VIEW_HISTORY_AUDIT,
    PermissionKey.VIEW_MEMBERS,
    PermissionKey.VIEW_MEMBER_WORKLOAD,
    PermissionKey.VIEW_MEMBER_ACTIVE_STATUS,
    PermissionKey.VIEW_MEMBER_DETAIL,
    PermissionKey.FILTER_MEMBERS,
    PermissionKey.VIEW_NOTIFICATIONS,
    PermissionKey.VIEW_ANNOUNCEMENTS,
    PermissionKey.SEND_LINE_NOTIFICATION,
    PermissionKey.CREATE_STORE_ISSUE,
  ]),
  [RoleName.ENGINEER]: new Set([
    PermissionKey.LOGIN,
    PermissionKey.VIEW_DASHBOARD,
    PermissionKey.VIEW_ALL_WORK,
    PermissionKey.VIEW_PROFILE,
    PermissionKey.UPDATE_OWN_PROFILE,
    PermissionKey.CREATE_INTERNAL_REQUEST,
    PermissionKey.TRACK_WORK,
    PermissionKey.VIEW_WORK_DETAIL,
    PermissionKey.UPDATE_REQUEST_BEFORE_CLAIM,
    PermissionKey.ATTACH_WORK_FILES,
    PermissionKey.UPDATE_PRIORITY,
    PermissionKey.UPDATE_WORK_ZONE,
    PermissionKey.CLAIM_WORK,
    PermissionKey.START_WORK,
    PermissionKey.UPDATE_WORK_PROGRESS,
    PermissionKey.RECORD_FIX_METHOD,
    PermissionKey.RECORD_SPARE_PARTS,
    PermissionKey.ATTACH_BEFORE_AFTER_PHOTOS,
    PermissionKey.SUBMIT_WAITING_CLOSE,
    PermissionKey.REOPEN_WAITING_CLOSE,
    PermissionKey.VIEW_TECHNICIAN_CLOSE_DETAIL,
    PermissionKey.CANCEL_WORK,
    PermissionKey.RECORD_CANCEL_REASON,
    PermissionKey.REVIEW_WORK,
    PermissionKey.CLOSE_WORK,
    PermissionKey.PRINT_COMPLETION_DOCUMENT,
    PermissionKey.EXPORT_COMPLETION_PDF,
    PermissionKey.VIEW_REPORTS,
    PermissionKey.VIEW_PLANT_KPI,
    PermissionKey.VIEW_MTTR_MTBF,
    PermissionKey.VIEW_BACKLOG_OVERDUE,
    PermissionKey.VIEW_REPORT_BY_CATEGORY,
    PermissionKey.VIEW_REPORT_BY_ZONE,
    PermissionKey.VIEW_REPORT_BY_ASSIGNEE,
    PermissionKey.VIEW_HISTORY_AUDIT,
    PermissionKey.VIEW_MEMBERS,
    PermissionKey.VIEW_MEMBER_WORKLOAD,
    PermissionKey.VIEW_MEMBER_ACTIVE_STATUS,
    PermissionKey.VIEW_MEMBER_DETAIL,
    PermissionKey.FILTER_MEMBERS,
    PermissionKey.VIEW_NOTIFICATIONS,
    PermissionKey.VIEW_ANNOUNCEMENTS,
    PermissionKey.SEND_LINE_NOTIFICATION,
    PermissionKey.CREATE_STORE_ISSUE,
    PermissionKey.APPROVE_STORE_ISSUE,
    PermissionKey.VIEW_STORE_TRACKING,
  ]),
  [RoleName.TECHNICIAN]: new Set([
    PermissionKey.LOGIN,
    PermissionKey.VIEW_DASHBOARD,
    PermissionKey.VIEW_ALL_WORK,
    PermissionKey.VIEW_PROFILE,
    PermissionKey.UPDATE_OWN_PROFILE,
    PermissionKey.CREATE_INTERNAL_REQUEST,
    PermissionKey.TRACK_WORK,
    PermissionKey.VIEW_WORK_DETAIL,
    PermissionKey.ATTACH_WORK_FILES,
    PermissionKey.CLAIM_WORK,
    PermissionKey.START_WORK,
    PermissionKey.UPDATE_WORK_PROGRESS,
    PermissionKey.RECORD_FIX_METHOD,
    PermissionKey.RECORD_SPARE_PARTS,
    PermissionKey.ATTACH_BEFORE_AFTER_PHOTOS,
    PermissionKey.SUBMIT_WAITING_CLOSE,
    PermissionKey.PRINT_COMPLETION_DOCUMENT,
    PermissionKey.EXPORT_COMPLETION_PDF,
    PermissionKey.VIEW_REPORTS,
    PermissionKey.VIEW_PLANT_KPI,
    PermissionKey.VIEW_REPORT_BY_CATEGORY,
    PermissionKey.VIEW_REPORT_BY_ZONE,
    PermissionKey.VIEW_REPORT_BY_ASSIGNEE,
    PermissionKey.VIEW_MEMBERS,
    PermissionKey.VIEW_MEMBER_DETAIL,
    PermissionKey.FILTER_MEMBERS,
    PermissionKey.VIEW_NOTIFICATIONS,
    PermissionKey.VIEW_ANNOUNCEMENTS,
    PermissionKey.SEND_LINE_NOTIFICATION,
    PermissionKey.CREATE_STORE_ISSUE,
    PermissionKey.VIEW_STORE_TRACKING,
  ]),
  [RoleName.STORE_OFFICER]: new Set([
    PermissionKey.LOGIN,
    PermissionKey.VIEW_PROFILE,
    PermissionKey.UPDATE_OWN_PROFILE,
    PermissionKey.VIEW_STORE_DASHBOARD,
    PermissionKey.VIEW_STORE_STOCK,
    PermissionKey.MANAGE_STORE,
    PermissionKey.MANAGE_SPARE_PARTS,
    PermissionKey.RECEIVE_STOCK,
    PermissionKey.ADJUST_STOCK,
    PermissionKey.CREATE_STORE_ISSUE,
    PermissionKey.ISSUE_STOCK,
    PermissionKey.VIEW_STORE_TRACKING,
    PermissionKey.VIEW_STORE_REPORTS,
  ]),
  [RoleName.VISITOR]: new Set([
    PermissionKey.LOGIN,
    PermissionKey.VIEW_DASHBOARD,
    PermissionKey.VIEW_ALL_WORK,
    PermissionKey.VIEW_PROFILE,
    PermissionKey.UPDATE_OWN_PROFILE,
    PermissionKey.VIEW_WORK_DETAIL,
    PermissionKey.VIEW_MEMBERS,
    PermissionKey.VIEW_MEMBER_DETAIL,
    PermissionKey.FILTER_MEMBERS,
    PermissionKey.VIEW_ANNOUNCEMENTS,
  ]),
  [PublicRoleName.PUBLIC_REQUESTER]: new Set([
    PermissionKey.ACCESS_PUBLIC_QR,
    PermissionKey.CREATE_PUBLIC_REQUEST,
    PermissionKey.TRACK_WORK,
    PermissionKey.ATTACH_WORK_FILES,
    PermissionKey.SEND_LINE_NOTIFICATION,
  ]),
};

export function permissionDefaultForRole(role: string, permissionKey: PermissionKey) {
  const normalizedRole = isSiteAdminRole(role) ? RoleName.SITE_ADMIN : role;
  return Boolean(alwaysAllowedByRole[normalizedRole as PermissionRole]?.has(permissionKey));
}

export function isSiteAdminConfigurablePermission(permissionKey: string): permissionKey is (typeof SITE_ADMIN_CONFIGURABLE_PERMISSIONS)[number] {
  return SITE_ADMIN_CONFIGURABLE_PERMISSIONS.includes(permissionKey as (typeof SITE_ADMIN_CONFIGURABLE_PERMISSIONS)[number]);
}

export function canUsePermission(
  actor: { id?: string; role: string; plantId?: string | null },
  permissionKey: PermissionKey,
  siteAdminPermissions: SiteAdminPermissionRecord[] = [],
) {
  if (actor.role === RoleName.ADMIN) return true;
  if (!isSiteAdminRole(actor.role)) return permissionDefaultForRole(actor.role, permissionKey);
  if (permissionDefaultForRole(actor.role, permissionKey)) return true;
  if (!actor.id || !actor.plantId || !isSiteAdminConfigurablePermission(permissionKey)) return false;

  return siteAdminPermissions.some(
    (permission) =>
      permission.enabled &&
      permission.userId === actor.id &&
      permission.plantId === actor.plantId &&
      permission.permissionKey === permissionKey,
  );
}

export function canUseUserPermission(user: PermissionUserContext, permissionKey: PermissionKey) {
  return canUsePermission(
    { id: user.id, role: user.role, plantId: user.plantId },
    permissionKey,
    user.siteAdminPermissions ?? [],
  );
}
