import { AlertTriangle, CalendarClock, Plus, Trash2, X } from "lucide-react";
import { PmConfirmPlanDialog } from "./pm-confirm-plan-dialog";

type Group = { id: string; code: string; name: string };
type Preview = { assets: Array<{ id: string; code: string | null; name: string; eligible: boolean; sources: Group[] }>; duplicateAssets: Array<{ id: string }>; emptyGroups: Group[]; retiredGroups: Group[]; ineligibleAssets: Array<{ id: string; code: string | null; name: string }>; eligibleAssetCount: number };

export function PmPlanEditor({ plan, groups, preview, scope, calendarView = "month", canManage, actions }: {
  plan: { id: string; plannedDateKey: string; status: string; submissionKey: string | null; draftGroups: Array<{ pmGroup: Group }> };
  groups: Group[];
  preview: Preview;
  scope: { organizationId: string; plantId: string };
  calendarView?: "month" | "day";
  canManage: boolean;
  actions: { add: (data: FormData) => void | Promise<void>; remove: (data: FormData) => void | Promise<void>; reschedule: (data: FormData) => void | Promise<void>; deletePlan: (data: FormData) => void | Promise<void>; confirm: (data: FormData) => void | Promise<void> };
}) {
  const chosen = new Set(plan.draftGroups.map(item => item.pmGroup.id));
  const available = groups.filter(group => !chosen.has(group.id));
  const hidden = () => <><input name="organizationId" type="hidden" value={scope.organizationId} /><input name="plantId" type="hidden" value={scope.plantId} /><input name="planId" type="hidden" value={plan.id} /><input name="currentDate" type="hidden" value={plan.plannedDateKey} /><input name="calendarView" type="hidden" value={calendarView} /></>;
  return <aside aria-label="แก้ไขแผน PM" className="min-w-0 rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow)]">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold text-[var(--primary)]">Daily PM Draft</p><h2 className="mt-1 text-2xl font-extrabold">{plan.plannedDateKey}</h2></div><span className="rounded-full bg-amber-500/10 px-3 py-1 text-xs font-bold text-amber-700">{plan.status}</span></div>
    <section className="mt-5 grid gap-2" aria-label="PM Groups ที่เลือก"><h3 className="font-extrabold">PM Groups</h3>{plan.draftGroups.map(({ pmGroup }) => <div className="flex items-center justify-between gap-2 rounded-2xl bg-[var(--soft)] p-3" key={pmGroup.id}><span className="min-w-0"><strong className="block truncate">{pmGroup.code}</strong><span className="text-sm text-[var(--muted)]">{pmGroup.name}</span></span>{canManage ? <form action={actions.remove}>{hidden()}<input name="groupId" type="hidden" value={pmGroup.id} /><button aria-label={`นำ ${pmGroup.code} ออกจากแผน`} className="grid min-h-11 min-w-11 place-items-center rounded-xl border border-[var(--line)]"><X size={18} /></button></form> : null}</div>)}{!plan.draftGroups.length ? <p className="rounded-2xl border border-dashed border-[var(--line)] p-4 text-sm text-[var(--muted)]">ยังไม่ได้เลือก PM Group</p> : null}</section>
    {canManage ? <form action={actions.add} className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]">{hidden()}<label className="grid gap-1 text-sm font-bold"><span>+ เพิ่ม PM Group</span><select className="min-h-12 min-w-0 rounded-2xl border border-[var(--line)] bg-[var(--soft)] px-3" disabled={!available.length} name="groupId" required><option value="">เลือก PM Group</option>{available.map(group => <option key={group.id} value={group.id}>{group.code} · {group.name}</option>)}</select></label><button className="mt-auto inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-[var(--primary)] px-4 font-bold text-white" disabled={!available.length}><Plus size={18} />เพิ่ม</button></form> : null}
    <section className="mt-5 border-t border-[var(--line)] pt-5"><h3 className="font-extrabold">Asset Preview · {preview.eligibleAssetCount} รายการ</h3>{preview.emptyGroups.length || preview.retiredGroups.length || preview.ineligibleAssets.length ? <div className="mt-3 rounded-2xl bg-amber-500/10 p-3 text-sm text-amber-800" role="status"><AlertTriangle className="mr-2 inline" size={17} />พบ Empty group {preview.emptyGroups.length}, ปิดใช้งาน {preview.retiredGroups.length}, Asset ไม่พร้อม {preview.ineligibleAssets.length}</div> : null}<div className="mt-3 max-h-72 overflow-y-auto">{preview.assets.map(asset => <div className="border-b border-[var(--line)] py-3 text-sm" key={asset.id}><strong>{asset.code ?? "ไม่มีรหัส"} · {asset.name}</strong><span className="block text-xs text-[var(--muted)]">จาก {asset.sources.map(source => source.code).join(", ")}{asset.sources.length > 1 ? " · ซ้ำหลายกลุ่ม (รวมเป็นงานเดียวเมื่อยืนยัน)" : ""}{!asset.eligible ? " · ไม่พร้อมใช้งาน" : ""}</span></div>)}</div></section>
    {canManage ? <div className="mt-5 grid gap-3 border-t border-[var(--line)] pt-5"><PmConfirmPlanDialog action={actions.confirm} eligibleAssetCount={preview.eligibleAssetCount} emptyGroupCount={preview.emptyGroups.length} hiddenFields={[{ name: "organizationId", value: scope.organizationId }, { name: "plantId", value: scope.plantId }, { name: "planId", value: plan.id }, { name: "currentDate", value: plan.plannedDateKey }, { name: "calendarView", value: calendarView }, { name: "submissionKey", value: plan.submissionKey ?? "" }]} /><form action={actions.reschedule} className="grid gap-2 sm:grid-cols-[1fr_auto]">{hidden()}<label className="grid gap-1 text-sm font-bold">ย้ายวัน<input className="min-h-12 rounded-2xl border border-[var(--line)] bg-[var(--soft)] px-3" defaultValue={plan.plannedDateKey} name="plannedDateKey" required type="date" /></label><button className="mt-auto inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl border border-[var(--line)] px-4 font-bold"><CalendarClock size={18} />ย้ายวัน</button></form><form action={actions.deletePlan}>{hidden()}<button className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl border border-red-500/40 text-sm font-bold text-red-700"><Trash2 size={18} />ลบ Draft</button></form></div> : null}
  </aside>;
}
