import { redirect } from "next/navigation";
import { Download, FileSpreadsheet } from "lucide-react";
import { AppShell } from "../../../components/app-shell";
import { AdminScopeHiddenFields } from "../../../components/admin-site-scope-selector";
import { AssetImportPreview } from "../../../components/asset-import-preview";
import { requireUser } from "../../../lib/session";
import { db } from "../../../lib/db";
import { canManageAssets } from "../../../modules/auth/permission";
import { resolveAssetScope } from "../../../modules/assets/asset-scope";
import { adminScopeSearchFromFormData } from "../../../modules/admin/admin-site-scope";
import { createRegisteredAsset } from "../../../modules/assets/asset-service";

type Row=Record<string,string|number|boolean|null>;
const cell=(row:Row,key:string)=>String(row[key]??"").trim();
async function importAssets(formData:FormData){"use server";const user=await requireUser();if(!canManageAssets(user))redirect("/assets");const scope=await resolveAssetScope(user,adminScopeSearchFromFormData(formData));let rows:Row[]=[];try{rows=JSON.parse(String(formData.get("rowsJson")||"[]"))}catch{redirect("/assets/import?error=invalid-json")};if(!rows.length||rows.length>1000)redirect("/assets/import?error=invalid-count");
  const [families,classes,types,zones]=await Promise.all([db.assetFamily.findMany({where:{plantId:scope.plant.id,active:true}}),db.assetClass.findMany({where:{plantId:scope.plant.id,active:true}}),db.assetType.findMany({where:{plantId:scope.plant.id,active:true}}),db.zone.findMany({where:{plantId:scope.plant.id,active:true}})]);
  const prepared=rows.map((row,index)=>{const family=families.find(x=>x.code.toUpperCase()===cell(row,"Family Code").toUpperCase());const assetClass=classes.find(x=>[x.nameTh,x.nameEn||""].some(v=>v.toLowerCase()===cell(row,"Asset Class").toLowerCase()));const typeCode=cell(row,"Asset Type");const assetType=typeCode?types.find(x=>x.code.toUpperCase()===typeCode.toUpperCase()):null;const zoneName=cell(row,"Zone");const zone=zoneName?zones.find(x=>x.name.toLowerCase()===zoneName.toLowerCase()):null;if(!family||!assetClass||(typeCode&&!assetType)||(zoneName&&!zone))throw new Error(`แถว ${index+2}: ไม่พบ Master Data ที่อ้างอิง`);return{row,family,assetClass,assetType,zone}});
  let created=0;try{for(const item of prepared){const parentCode=cell(item.row,"Parent Code");const parent=parentCode?await db.asset.findFirst({where:{plantId:scope.plant.id,code:parentCode,parentId:null,registrationStatus:"ACTIVE"}}):null;if(parentCode&&!parent)throw new Error(`ไม่พบ Parent Code ${parentCode}`);const nameEn=cell(item.row,"English Name");await createRegisteredAsset({plantId:scope.plant.id,familyId:item.family.id,assetClassId:item.assetClass.id,assetTypeId:item.assetType?.id||null,zoneId:item.zone?.id||null,parentId:parent?.id||null,componentCode:cell(item.row,"Component Code")||null,nameTh:cell(item.row,"ชื่อภาษาไทย")||nameEn,nameEn,installationLocation:cell(item.row,"Installation Location"),manufacturer:cell(item.row,"Manufacturer"),model:cell(item.row,"Model"),serialNumber:cell(item.row,"Serial Number"),operatingStatus:cell(item.row,"Operating Status")||"IN_SERVICE",criticality:cell(item.row,"Criticality")||"MEDIUM"});created++}}catch(e){redirect(`/assets/import?organizationId=${scope.organization.id}&plantId=${scope.plant.id}&error=${encodeURIComponent(e instanceof Error?e.message:"Import ไม่สำเร็จ")}`)}redirect(`/assets?organizationId=${scope.organization.id}&plantId=${scope.plant.id}&imported=${created}`)}

export default async function AssetImportPage({searchParams}:{searchParams:Promise<{organizationId?:string;plantId?:string;error?:string}>}){const user=await requireUser();if(!canManageAssets(user))redirect("/assets");const query=await searchParams;const scope=await resolveAssetScope(user,query);return <AppShell><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-emerald-600">Asset import</p><h1 className="mt-2 text-3xl font-black">นำเข้า Assets จาก Excel</h1><p className="mt-2 text-sm text-[var(--muted)]">นำเข้า Parent ก่อน แล้วจึงนำเข้า Child โดยอ้างอิง Parent Code</p></div><a href="/assets/import/template" className="flex min-h-11 items-center gap-2 rounded-xl border border-[var(--line)] px-4 text-sm font-bold hover:bg-[var(--soft)]"><Download size={17}/>ดาวน์โหลด Template</a></header>{query.error?<p role="alert" className="mt-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm font-bold text-red-700">{decodeURIComponent(query.error)}</p>:null}<section className="mt-6 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><FileSpreadsheet className="text-emerald-600"/><div><h2 className="font-black">Preview และตรวจสอบ</h2><p className="text-xs text-[var(--muted)]">ไม่รับรหัส Asset จากไฟล์ ระบบจะสร้างเลขลำดับให้เอง</p></div></div><form action={importAssets}><AdminScopeHiddenFields scope={scope}/><AssetImportPreview/></form></section></AppShell>}
