import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import QRCode from "qrcode";
import { headers } from "next/headers";
import { Activity, Box, Boxes, Camera, CheckCircle2, CircleAlert, ClipboardCheck, Cpu, FileText, GitBranch, ImageIcon, Pencil, QrCode, Wrench } from "lucide-react";
import { AppShell } from "../../../components/app-shell";
import { AssetQrActions } from "../../../components/asset-qr-actions";
import { db } from "../../../lib/db";
import { getPublicBaseUrl } from "../../../lib/public-url";
import { requireUser } from "../../../lib/session";
import { formatThaiDate } from "../../../lib/date-time/bangkok-time";
import { saveAssetFile } from "../../../lib/file-storage";
import { canManageAssetDocuments, canManageAssets, canViewAssets } from "../../../modules/auth/permission";
import { assetStatusLabel, criticalityLabel } from "../../../modules/assets/asset-service";
async function uploadAssetImage(formData:FormData){"use server";const user=await requireUser();if(!canManageAssets(user))redirect("/assets");const id=String(formData.get("assetId"));const asset=await db.asset.findUniqueOrThrow({where:{id}});if(user.role!=="ADMIN"&&user.role!=="ORGANIZATION_ADMIN"&&user.plantId!==asset.plantId)redirect("/assets");const file=formData.get("file");if(!(file instanceof File)||!file.size)redirect(`/assets/${id}`);const saved=await saveAssetFile(id,file,"image");await db.asset.update({where:{id},data:{imageFileName:saved.fileName,imageMimeType:saved.mimeType,imageFileSize:saved.fileSize,imageStoragePath:saved.storagePath}});redirect(`/assets/${id}?tab=identity`)}
async function uploadAssetDocument(formData:FormData){"use server";const user=await requireUser();if(!canManageAssetDocuments(user))redirect("/assets");const id=String(formData.get("assetId"));const asset=await db.asset.findUniqueOrThrow({where:{id}});if(user.role!=="ADMIN"&&user.role!=="ORGANIZATION_ADMIN"&&user.plantId!==asset.plantId)redirect("/assets");const file=formData.get("file");if(!(file instanceof File)||!file.size)redirect(`/assets/${id}?tab=identity`);const saved=await saveAssetFile(id,file,"document");const category=String(formData.get("category")||"OTHER");const latest=await db.assetDocument.aggregate({where:{assetId:id,category,title:String(formData.get("title"))},_max:{version:true}});await db.assetDocument.create({data:{assetId:id,category,title:String(formData.get("title")),revision:String(formData.get("revision")||"")||null,note:String(formData.get("note")||"")||null,publicVisible:formData.get("publicVisible")==="on",version:(latest._max.version||0)+1,...saved}});redirect(`/assets/${id}?tab=identity`)}

export default async function AssetDetailPage({ params, searchParams }: { params: Promise<{id:string}>; searchParams: Promise<{tab?:string;created?:string}> }) {
  const user=await requireUser(); if(!canViewAssets(user)) redirect("/dashboardcm");
  const {id}=await params; const query=await searchParams;
  const asset=await db.asset.findUnique({where:{id},include:{plant:true,family:true,assetClass:true,assetType:{include:{fields:{where:{active:true},orderBy:{sortOrder:"asc"}}}},zone:true,parent:{include:{family:true,assetClass:true,assetType:true}},children:{include:{assetType:true},orderBy:{componentCode:"asc"}},technicalValues:{include:{field:true},orderBy:{sortOrder:"asc"}},documents:{orderBy:{createdAt:"desc"}},cmWorks:{include:{category:true},orderBy:{createdAt:"desc"}}}}); if(!asset)notFound();
  if(user.role!=="ADMIN"&&user.role!=="ORGANIZATION_ADMIN"&&user.plantId!==asset.plantId)redirect("/assets");
  const hierarchyParent=asset.parent??asset; const tab=query.tab==="maintenance"?"maintenance":"identity"; const requestHeaders=await headers(); const publicUrl=`${getPublicBaseUrl({ forwardedHost: requestHeaders.get("x-forwarded-host"), forwardedProto: requestHeaders.get("x-forwarded-proto"), host: requestHeaders.get("host") })}/asset-qr/${hierarchyParent.publicToken}`; const qr=await QRCode.toDataURL(publicUrl,{width:720,margin:2,color:{dark:"#064e3b",light:"#ffffff"}});
  const qrDetails={code:hierarchyParent.code||"-",assetClass:hierarchyParent.assetClass.nameEn||hierarchyParent.assetClass.nameTh,assetType:hierarchyParent.assetType?.nameEn||hierarchyParent.assetType?.nameTh||"ชุดเครื่องจักร",assetFamily:`${hierarchyParent.family.code} · ${hierarchyParent.family.nameEn||hierarchyParent.family.nameTh||"-"}`,assetName:hierarchyParent.nameEn||hierarchyParent.nameTh};
  const tabs=[{id:"identity",label:"ข้อมูลประจำเครื่อง",icon:Box},{id:"maintenance",label:"การบำรุงรักษา",icon:Wrench}];
  const latestCm=asset.cmWorks.find(work=>work.status==="CLOSED");

  const hierarchyChildren=asset.parent?await db.asset.findMany({where:{parentId:asset.parent.id},orderBy:{componentCode:"asc"},select:{id:true,code:true,nameTh:true,nameEn:true,componentCode:true,operatingStatus:true,assetType:{select:{code:true,nameTh:true}}}}):asset.children.map(child=>({id:child.id,code:child.code,nameTh:child.nameTh,nameEn:child.nameEn,componentCode:child.componentCode,operatingStatus:child.operatingStatus,assetType:child.assetType?{code:child.assetType.code,nameTh:child.assetType.nameTh}:null}));
  const repairChildren=hierarchyChildren.length?await db.asset.count({where:{id:{in:hierarchyChildren.map(child=>child.id)},operatingStatus:"UNDER_REPAIR"}}):0;
  return <AppShell>
    {query.created?<p className="mb-4 rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm font-bold text-emerald-700">สร้าง Asset และออกรหัสเรียบร้อยแล้ว</p>:null}
    <header className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex min-w-0 gap-4"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-2xl bg-emerald-500/10 text-emerald-600"><Boxes size={34}/></div><div className="min-w-0"><p className="font-mono text-sm font-black text-emerald-700 dark:text-emerald-400">{hierarchyParent.code}</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{hierarchyParent.nameEn||hierarchyParent.nameTh}</h1><p className="mt-1 text-sm text-[var(--muted)]">{hierarchyParent.nameEn&&hierarchyParent.nameTh!==hierarchyParent.nameEn?hierarchyParent.nameTh:asset.family.nameEn||"-"}</p><div className="mt-3 flex flex-wrap gap-2"><Badge>{assetStatusLabel(hierarchyParent.operatingStatus)}</Badge><Badge>{criticalityLabel(hierarchyParent.criticality)}</Badge><Badge>Parent Asset</Badge></div></div></div><div className="flex flex-wrap gap-2">{canManageAssets(user)?<Link href={`/assets/${asset.id}/edit`} className="flex min-h-11 items-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white hover:bg-emerald-700"><Pencil size={17}/>แก้ไข Asset</Link>:null}<Link href="/assets" className="rounded-xl border border-[var(--line)] px-4 py-2 text-sm font-bold hover:bg-[var(--soft)]">กลับทะเบียน</Link></div></div>
      {repairChildren?<div className="mt-4 flex items-center gap-2 rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm font-bold text-amber-700"><CircleAlert size={18}/>มีอุปกรณ์ย่อยปิดซ่อม {repairChildren} รายการ — สถานะ Asset แม่ไม่ถูกเปลี่ยนอัตโนมัติ</div>:null}
    </header>
    <nav aria-label="Asset detail tabs" className="mt-5 flex overflow-x-auto border-b border-[var(--line)]">{tabs.map(item=>{const Icon=item.icon;return <Link key={item.id} href={`/assets/${asset.id}?tab=${item.id}`} aria-current={tab===item.id?"page":undefined} className={`flex min-h-12 shrink-0 items-center gap-2 border-b-2 px-4 text-sm font-bold transition ${tab===item.id?"border-emerald-600 text-emerald-700":"border-transparent text-[var(--muted)] hover:text-[var(--ink)]"}`}><Icon size={17}/>{item.label}</Link>})}</nav>
    <section className="asset-detail-content mt-5">
      {tab==="identity"?<div className="grid gap-4"><style>{`.asset-detail-content > .grid.gap-5 { display: none; }`}</style>
        <div className="grid gap-4 xl:grid-cols-[minmax(280px,0.92fr)_minmax(390px,1.15fr)_320px]">
          <Card title="รูปประจำเครื่อง" icon={ImageIcon}>
            <div className="relative overflow-hidden rounded-xl bg-[var(--soft)]">
              {hierarchyParent.imageStoragePath?<img src={`/asset-images/${hierarchyParent.id}`} alt={`รูป ${hierarchyParent.nameTh}`} className="aspect-[4/3] w-full object-cover"/>:<div className="grid aspect-[4/3] place-items-center text-center text-[var(--muted)]"><div><ImageIcon className="mx-auto" size={40}/><p className="mt-2 text-sm font-bold">ยังไม่มีรูปประจำเครื่องแม่</p></div></div>}
              <span className="absolute bottom-3 left-3 rounded-lg bg-slate-950/80 px-3 py-1.5 font-mono text-sm font-black text-white">{hierarchyParent.code}</span>
            </div>
            {canManageAssets(user)?<form action={uploadAssetImage} className="mt-3 grid gap-2"><input type="hidden" name="assetId" value={hierarchyParent.id}/><input required type="file" accept="image/png,image/jpeg,image/webp" name="file" className="min-h-11 w-full rounded-xl border border-[var(--line)] p-2 text-sm"/><button type="submit" className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white hover:bg-emerald-700"><Camera size={17}/>บันทึกรูปภาพ</button></form>:null}
            <AssetCodeTree parent={{id:hierarchyParent.id,code:hierarchyParent.code||"-",name:hierarchyParent.nameEn||hierarchyParent.nameTh}} children={hierarchyChildren.map(child=>({id:child.id,code:child.code||"-",name:child.nameEn||child.nameTh}))} currentId={asset.id}/>
          </Card>
          <IdentityCard><AssetTypeTabs parent={{id:hierarchyParent.id,active:asset.id===hierarchyParent.id}} children={hierarchyChildren.map(child=>({id:child.id,label:child.assetType?.code||child.componentCode||"Asset",active:asset.id===child.id}))}/><InfoTable items={[["รหัสเครื่องจักร",asset.code],["Asset Class",asset.assetClass.nameTh],["Asset Type",asset.assetType?.nameTh||"ชุดเครื่องจักร"],["Asset Family",`${asset.family.code} · ${asset.family.nameTh}`],["Zone",asset.zone?.name],["ตำแหน่งติดตั้ง",asset.installationLocation],["ผู้ผลิต",asset.manufacturer],["รุ่น",asset.model],["Serial Number",asset.serialNumber],["วันที่ติดตั้ง",formatDate(asset.installedAt)],["วันที่เริ่มใช้งาน",formatDate(asset.commissionedAt)]]}/><div className="mt-5 border-t border-[var(--line)] pt-5"><div className="mb-3 flex items-center gap-2"><Cpu className="text-emerald-600" size={18}/><h3 className="font-black">ข้อมูลทางเทคนิค</h3></div><div className="grid gap-3 md:grid-cols-2">{asset.assetType?.fields.map(field=>{const value=asset.technicalValues.find(v=>v.fieldId===field.id);return <div key={field.id} className="rounded-xl bg-[var(--soft)] p-4"><p className="text-xs font-bold text-[var(--muted)]">{field.labelTh}{field.labelEn?` / ${field.labelEn}`:""}</p><p className="mt-1 text-lg font-black">{value?.value||"ยังไม่ระบุ"} {value?.value&&field.unit?<span className="text-sm font-medium text-[var(--muted)]">{field.unit}</span>:null}</p></div>})}{asset.technicalValues.filter(v=>!v.fieldId).map(v=><div key={v.id} className="rounded-xl bg-[var(--soft)] p-4"><p className="text-xs font-bold text-[var(--muted)]">{v.customLabel}</p><p className="mt-1 text-lg font-black">{v.value||"-"} {v.unit}</p></div>)}</div>{!asset.assetType?.fields.length&&!asset.technicalValues.length?<Empty icon={Cpu} title="ยังไม่มีข้อมูลทางเทคนิค" text="กำหนด Technical Template ใน Asset Master Data หรือเพิ่ม Custom Field"/>:null}</div></IdentityCard>
          <div className="grid content-start gap-4">
            <Card title="QR Code ประจำเครื่อง" icon={QrCode}><img src={qr} alt={`QR Code สำหรับ ${hierarchyParent.code}`} className="mx-auto aspect-square w-full max-w-48 rounded-xl bg-white p-2"/><div className="mt-3"><AssetQrActions image={qr} url={publicUrl} code={hierarchyParent.code||"asset"} details={qrDetails}/></div></Card>
            <Card title="สรุปสถานะ" icon={Activity}><div className="flex min-h-11 items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-4 font-bold text-emerald-700"><CheckCircle2 size={20}/>{assetStatusLabel(asset.operatingStatus)}</div><div className="mt-2 grid grid-cols-2 gap-2"><Metric label="อุปกรณ์ย่อย" value={hierarchyChildren.length} tone="green"/><Metric label="เปิดซ่อม" value={repairChildren} tone="red"/></div><div className="mt-2 rounded-xl border border-[var(--line)] px-3 py-2 text-center text-sm font-bold">{asset.parent?`กำลังดู ${asset.code}`:"Parent Asset"}</div></Card>
          </div>
        </div>
      </div>:null}
      {tab==="identity"?<div className="grid gap-5 xl:grid-cols-[1fr_320px]"><div className="grid gap-5"><Card title="ข้อมูลประจำเครื่อง" icon={Box}>{asset.imageStoragePath?<img src={`/asset-images/${asset.id}`} alt={`รูป ${asset.nameTh}`} className="mb-5 aspect-[16/8] w-full rounded-xl object-cover"/>:null}{canManageAssets(user)?<form action={uploadAssetImage} className="mb-5 grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><input type="hidden" name="assetId" value={asset.id}/><input required type="file" accept="image/png,image/jpeg,image/webp" name="file" aria-label="เลือกรูปภาพ Asset" className="min-h-11 w-full rounded-xl border border-[var(--line)] p-2 text-sm"/><button type="submit" className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-5 text-sm font-bold text-white hover:bg-emerald-700"><Camera size={17}/>บันทึกรูปภาพ</button><p className="text-xs text-[var(--muted)] sm:col-span-2">รองรับ PNG, JPG และ WebP โดยรูปใหม่จะแทนที่รูปเดิม</p></form>:null}<InfoGrid items={[["รหัสเครื่องจักร",asset.code],["Asset Class",asset.assetClass.nameTh],["Asset Type",asset.assetType?.nameTh||"ชุดเครื่องจักร"],["Asset Family",`${asset.family.code} · ${asset.family.nameTh}`],["Zone",asset.zone?.name],["ตำแหน่งติดตั้ง",asset.installationLocation],["ผู้ผลิต",asset.manufacturer],["รุ่น",asset.model],["Serial Number",asset.serialNumber],["วันที่ติดตั้ง",formatDate(asset.installedAt)],["วันที่เริ่มใช้งาน",formatDate(asset.commissionedAt)]]}/></Card>{asset.children.length?<Card title="อุปกรณ์ย่อย" icon={Boxes}><div className="grid gap-2">{asset.children.map(child=><Link key={child.id} href={`/assets/${child.id}`} className="flex min-h-12 items-center justify-between rounded-xl bg-[var(--soft)] px-4 hover:ring-1 hover:ring-emerald-500"><span><span className="font-mono font-bold text-emerald-700">{child.code}</span> · {child.nameTh}</span><span className="text-xs font-bold">{assetStatusLabel(child.operatingStatus)}</span></Link>)}</div></Card>:null}</div><Card title="QR Code ประจำเครื่อง" icon={QrCode}><img src={qr} alt={`QR Code สำหรับ ${asset.code}`} className="mx-auto aspect-square w-full max-w-64 rounded-xl bg-white p-2"/><p className="mt-3 break-all text-center text-xs text-[var(--muted)]">เปิดดูข้อมูลได้โดยไม่ต้อง Login</p><div className="mt-4"><AssetQrActions image={qr} url={publicUrl} code={asset.code||"asset"}/></div></Card></div>:null}
      {tab==="identity"?<div className="mt-5"><Card title="เอกสารประจำเครื่อง" icon={FileText}>{canManageAssetDocuments(user)?<form action={uploadAssetDocument} className="mb-5 grid gap-3 rounded-xl border border-[var(--line)] bg-[var(--soft)] p-4 md:grid-cols-2"><input type="hidden" name="assetId" value={asset.id}/><select name="category" className={formInput}><option value="NAMEPLATE">Nameplate</option><option value="MANUAL">คู่มือการใช้งาน</option><option value="DATASHEET">Datasheet</option><option value="ELECTRICAL_DRAWING">แบบไฟฟ้า</option><option value="MECHANICAL_DRAWING">แบบเครื่องกล</option><option value="TEST_RESULT">ผลการทดสอบ</option><option value="WARRANTY">ใบรับประกัน</option><option value="OVERHAUL_REPORT">รายงานซ่อมใหญ่</option><option value="OTHER">อื่น ๆ</option></select><input required name="title" className={formInput} placeholder="ชื่อเอกสาร"/><input name="revision" className={formInput} placeholder="Revision"/><input required type="file" name="file" className={formInput} accept=".pdf,.docx,.xlsx,image/*"/><textarea name="note" className={`${formInput} min-h-20`} placeholder="หมายเหตุ"/><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="publicVisible"/> เปิดเอกสารนี้ผ่าน QR</label><button className="min-h-11 rounded-xl bg-emerald-600 px-4 font-bold text-white hover:bg-emerald-700">อัปโหลดเอกสาร</button></form>:null}{asset.documents.length?<div className="grid gap-2">{asset.documents.map(doc=><a key={doc.id} href={`/asset-files/${doc.id}`} className="flex items-center justify-between rounded-xl bg-[var(--soft)] p-4 hover:ring-1 hover:ring-emerald-500"><div><p className="font-bold">{doc.title}</p><p className="text-xs text-[var(--muted)]">{doc.category} · Rev {doc.revision||"-"} · Version {doc.version}</p></div><span className="text-xs font-bold">{doc.publicVisible?"Public QR":"Internal"}</span></a>)}</div>:<Empty icon={FileText} title="ยังไม่มีเอกสาร" text="รองรับ Nameplate, คู่มือ, Datasheet, แบบ, ผลทดสอบ, ใบรับประกัน และรายงานซ่อมใหญ่"/>}</Card></div>:null}
      {tab==="maintenance"?<div className="grid gap-5 lg:grid-cols-2"><Card title="CM — งานซ่อม" icon={Wrench}>{asset.cmWorks.length?<div className="grid gap-2">{asset.cmWorks.map(work=><Link key={work.id} href={`/work/${work.id}`} className="rounded-xl bg-[var(--soft)] p-4 hover:ring-1 hover:ring-emerald-500"><div className="flex justify-between gap-3"><p className="font-mono text-sm font-bold text-emerald-700">{work.number}</p><span className="text-xs font-bold">{work.status}</span></div><p className="mt-1 font-bold">{work.problemTitle}</p><p className="mt-1 text-xs text-[var(--muted)]">{formatDate(work.closedAt||work.createdAt)} · {work.category.name}</p></Link>)}</div>:<Empty icon={Wrench} title="ยังไม่มีประวัติ CM" text="CM ที่เลือก Asset นี้จะแสดงที่นี่โดยอัตโนมัติ"/>}</Card><Card title="PM — งานตามแผน" icon={ClipboardCheck}><Empty icon={ClipboardCheck} title="เตรียมพร้อมสำหรับ PM" text="โครงสร้าง Asset พร้อมเชื่อม PM Workflow ในระยะถัดไป"/></Card>{latestCm?<div className="lg:col-span-2 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm"><strong>ซ่อมล่าสุด:</strong> {formatDate(latestCm.closedAt)} · {latestCm.problemTitle}</div>:null}</div>:null}
    </section>
  </AppShell>
}
function IdentityCard({children}:{children:React.ReactNode}){return <section className="min-w-0 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-600"><Box size={20}/></span><h2 className="text-lg font-black">ข้อมูลประจำเครื่อง</h2></div>{children}</section>}
function AssetTypeTabs({parent,children}:{parent:{id:string;active:boolean};children:{id:string;label:string;active:boolean}[]}){const items=[{id:parent.id,label:"Parent",description:"เครื่องแม่",active:parent.active},...children.map((child,index)=>({...child,label:`Child ${index+1}`,description:child.label}))];return <nav aria-label="เลือกเครื่องแม่หรืออุปกรณ์ย่อย" className="mb-4 mt-4 grid grid-cols-2 border-b border-[var(--line)] sm:flex">{items.map((item)=><Link key={item.id} href={`/assets/${item.id}?tab=identity`} aria-current={item.active?"page":undefined} title={`${item.label} · ${item.description}`} className={`flex min-h-14 min-w-0 items-center justify-center gap-2 border-b-2 px-3 text-sm font-black transition sm:flex-1 ${item.active?"border-emerald-600 bg-emerald-500/5 text-emerald-700":"border-transparent text-[var(--muted)] hover:border-[var(--line)] hover:bg-[var(--soft)] hover:text-[var(--ink)]"}`}><GitBranch className="shrink-0" size={16}/><span className="min-w-0 text-left"><span className="block truncate">{item.label}</span><span className="block truncate text-[10px] font-bold opacity-70">{item.description}</span></span></Link>)}</nav>}
function AssetCodeTree({parent,children,currentId}:{parent:{id:string;code:string;name:string};children:{id:string;code:string;name:string}[];currentId:string}){return <div className="mt-4 border-t border-[var(--line)] pt-4"><p className="mb-2 text-xs font-bold text-[var(--muted)]">โครงสร้างรหัสเครื่องจักร</p><Link href={`/assets/${parent.id}?tab=identity`} aria-current={currentId===parent.id?"page":undefined} className={`flex min-h-11 items-center gap-2 rounded-lg px-2 hover:bg-[var(--soft)] ${currentId===parent.id?"bg-emerald-500/10 text-emerald-700":""}`}><GitBranch size={17}/><span className="min-w-0"><span className="block font-mono text-sm font-black">{parent.code}</span><span className="block truncate text-xs text-[var(--muted)]">{parent.name}</span></span></Link><div className="ml-4 border-l border-[var(--line)] pl-4">{children.map(child=><Link key={child.id} href={`/assets/${child.id}?tab=identity`} aria-current={currentId===child.id?"page":undefined} className={`relative flex min-h-11 items-center rounded-lg px-2 hover:bg-[var(--soft)] ${currentId===child.id?"bg-emerald-500/10 text-emerald-700":""}`}><span aria-hidden="true" className="absolute -left-4 top-1/2 w-3 border-t border-[var(--line)]"/><span className="min-w-0"><span className="block font-mono text-sm font-black">{child.code}</span><span className="block truncate text-xs text-[var(--muted)]">{child.name}</span></span></Link>)}</div></div>}
function Card({title,icon:Icon,children}:{title:string;icon:typeof Activity;children:React.ReactNode}){return <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-600"><Icon size={20}/></span><h2 className="text-lg font-black">{title}</h2></div>{children}</section>}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full bg-[var(--soft)] px-3 py-1 text-xs font-bold">{children}</span>}
function InfoGrid({items}:{items:(string|null|undefined)[][]}){return <dl className="grid gap-x-6 gap-y-4 sm:grid-cols-2">{items.map(([label,value])=><div key={label} className="border-b border-[var(--line)] pb-3"><dt className="text-xs font-bold text-[var(--muted)]">{label}</dt><dd className="mt-1 font-semibold">{value||"ยังไม่ระบุ"}</dd></div>)}</dl>}
function Empty({icon:Icon,title,text}:{icon:typeof Activity;title:string;text:string}){return <div className="py-12 text-center"><Icon className="mx-auto text-[var(--muted)]"/><h3 className="mt-3 font-bold">{title}</h3><p className="mt-1 text-sm text-[var(--muted)]">{text}</p></div>}
function InfoTable({items}:{items:(string|null|undefined)[][]}){return <dl>{items.map(([label,value])=><div key={label} className="grid grid-cols-[minmax(120px,0.85fr)_minmax(0,1.15fr)] border-t border-[var(--line)] py-2.5 text-sm first:border-t-0"><dt className="pr-4 text-[var(--muted)]">{label}</dt><dd className="border-l border-[var(--line)] pl-4 font-bold">{value||"ยังไม่ระบุ"}</dd></div>)}</dl>}
function Metric({label,value,tone}:{label:string;value:number;tone:"green"|"red"}){return <div className="rounded-xl border border-[var(--line)] p-3 text-center"><p className="text-xs text-[var(--muted)]">{label}</p><p className={`mt-1 text-2xl font-black ${tone==="green"?"text-emerald-600":"text-red-600"}`}>{value}</p></div>}
function formatDate(value:Date|null|undefined){return value?formatThaiDate(value):null}
const formInput="min-h-11 rounded-xl border border-[var(--line)] bg-[var(--surface)] px-3 py-2 text-sm";
