import { randomUUID } from "node:crypto";
import { redirect } from "next/navigation";
import { AdminScopeHiddenFields } from "../../components/admin-site-scope-selector";
import { AppShell } from "../../components/app-shell";
import { PmCalendar } from "../../components/pm/pm-calendar";
import { PmCalendarViewSwitcher, type PmCalendarView } from "../../components/pm/pm-calendar-view-switcher";
import { PmConfirmedPlanEditor } from "../../components/pm/pm-confirmed-plan-editor";
import { PmDayColumn } from "../../components/pm/pm-day-column";
import { PmPlanEditor } from "../../components/pm/pm-plan-editor";
import { PmRouteShell } from "../../components/pm/pm-route-shell";
import { db } from "../../lib/db";
import { getBangkokDateString } from "../../lib/date-time/bangkok-time";
import { requireUser } from "../../lib/session";
import { canManagePmGroups, canManagePmPlans, canViewPm } from "../../modules/auth/permission";
import { isIsoDateKey, isPmMonthKey, listPmCalendarPlans } from "../../modules/pm/pm-calendar-query";
import { resolvePmPageScope } from "../../modules/pm/pm-page-scope";
import { addDraftPmGroup, confirmPmPlan, createOrGetDraftPmPlan, deleteDraftPmPlan, getPmPlanEditor, previewDraftPmPlan, removeDraftPmGroup, rescheduleDraftPmPlan } from "../../modules/pm/pm-plan-service";
import { addAssetToConfirmedPmPlan, cancelConfirmedPmPlan, rescheduleConfirmedPmPlan } from "../../modules/pm/pm-work-service";

type Query = { organizationId?: string; plantId?: string; month?: string; date?: string; planId?: string; view?: string; saved?: string; error?: string };
function validDate(value: string | undefined, fallback: string) { return value && isIsoDateKey(value) ? value : fallback; }
function validMonth(value: string | undefined, fallback: string) { return value && isPmMonthKey(value) ? `${value}-01` : fallback; }
function validView(value: string | undefined): PmCalendarView { return value === "day" ? "day" : "month"; }
function errorMessage(error: unknown) { return error instanceof Error ? error.message : "Unable to save PM plan"; }
function url(scope: { organization: { id: string }; plant: { id: string }; calendarView?: PmCalendarView }, values: Record<string, string | undefined>) { const params = new URLSearchParams({ organizationId: scope.organization.id, plantId: scope.plant.id }); if (scope.calendarView) params.set("view", scope.calendarView); Object.entries(values).forEach(([key, value]) => { if (value) params.set(key, value); }); return `/dashboardpm?${params}`; }

async function actionContext(formData: FormData) { const user = await requireUser(); if (!canManagePmPlans(user)) redirect("/dashboardpm"); const resolvedScope = await resolvePmPageScope(user, { organizationId: String(formData.get("organizationId") ?? ""), plantId: String(formData.get("plantId") ?? "") }); const scope = { ...resolvedScope, calendarView: validView(String(formData.get("calendarView") ?? "")) }; return { user, scope, serviceScope: { organizationId: scope.organization.id, plantId: scope.plant.id }, planId: String(formData.get("planId") ?? "") }; }
async function createPlan(data: FormData) { "use server"; const { user, scope, serviceScope } = await actionContext(data); const date = String(data.get("plannedDateKey") ?? ""); let plan; try { plan = await createOrGetDraftPmPlan(user, { ...serviceScope, plannedDateKey: date, submissionKey: String(data.get("submissionKey") ?? "") }); } catch (error) { redirect(url(scope, { month: date.slice(0, 7), date, error: errorMessage(error) })); } redirect(url(scope, { month: date.slice(0, 7), date, planId: plan.id, saved: "created" })); }
async function addGroup(data: FormData) { "use server"; const { user, scope, serviceScope, planId } = await actionContext(data); const date = String(data.get("currentDate") ?? ""); try { await addDraftPmGroup(user, { ...serviceScope, planId, groupId: String(data.get("groupId") ?? "") }); } catch (error) { redirect(url(scope, { month: date.slice(0, 7), date, planId, error: errorMessage(error) })); } redirect(url(scope, { month: date.slice(0, 7), date, planId, saved: "group-added" })); }
async function removeGroup(data: FormData) { "use server"; const { user, scope, serviceScope, planId } = await actionContext(data); const date = String(data.get("currentDate") ?? ""); try { await removeDraftPmGroup(user, { ...serviceScope, planId, groupId: String(data.get("groupId") ?? "") }); } catch (error) { redirect(url(scope, { month: date.slice(0, 7), date, planId, error: errorMessage(error) })); } redirect(url(scope, { month: date.slice(0, 7), date, planId, saved: "group-removed" })); }
async function reschedule(data: FormData) { "use server"; const { user, scope, serviceScope, planId } = await actionContext(data); const currentDate = String(data.get("currentDate") ?? ""); const date = String(data.get("plannedDateKey") ?? ""); try { await rescheduleDraftPmPlan(user, { ...serviceScope, planId, plannedDateKey: date }); } catch (error) { redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, planId, error: errorMessage(error) })); } redirect(url(scope, { month: date.slice(0, 7), date, planId, saved: "rescheduled" })); }
async function deletePlan(data: FormData) { "use server"; const { user, scope, serviceScope, planId } = await actionContext(data); const currentDate = String(data.get("currentDate") ?? ""); try { await deleteDraftPmPlan(user, { ...serviceScope, planId }); } catch (error) { redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, planId, error: errorMessage(error) })); } redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, saved: "deleted" })); }
async function confirmPlan(data: FormData) { "use server"; const { user, scope, serviceScope, planId } = await actionContext(data); const currentDate = String(data.get("currentDate") ?? ""); try { await confirmPmPlan(user, { ...serviceScope, planId, submissionKey: String(data.get("submissionKey") ?? "") }); } catch (error) { redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, planId, error: errorMessage(error) })); } redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, planId, saved: "confirmed" })); }
async function addConfirmedAsset(data: FormData) { "use server"; const { user, scope, serviceScope, planId } = await actionContext(data); const currentDate = String(data.get("currentDate") ?? ""); try { await addAssetToConfirmedPmPlan(user, { ...serviceScope, planId, assetId: String(data.get("assetId") ?? ""), reason: String(data.get("reason") ?? "") }); } catch (error) { redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, planId, error: errorMessage(error) })); } redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, planId, saved: "asset-added" })); }
async function rescheduleConfirmed(data: FormData) { "use server"; const { user, scope, serviceScope, planId } = await actionContext(data); const currentDate = String(data.get("currentDate") ?? ""); const date = String(data.get("plannedDateKey") ?? ""); try { await rescheduleConfirmedPmPlan(user, { ...serviceScope, planId, plannedDateKey: date, reason: String(data.get("reason") ?? "") }); } catch (error) { redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, planId, error: errorMessage(error) })); } redirect(url(scope, { month: date.slice(0, 7), date, planId, saved: "confirmed-rescheduled" })); }
async function cancelConfirmed(data: FormData) { "use server"; const { user, scope, serviceScope, planId } = await actionContext(data); const currentDate = String(data.get("currentDate") ?? ""); try { await cancelConfirmedPmPlan(user, { ...serviceScope, planId, reason: String(data.get("reason") ?? "") }); } catch (error) { redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, planId, error: errorMessage(error) })); } redirect(url(scope, { month: currentDate.slice(0, 7), date: currentDate, saved: "confirmed-canceled" })); }

export default async function PmCalendarPage({ searchParams }: { searchParams: Promise<Query> }) {
  const user = await requireUser(); if (!canViewPm(user)) redirect("/dashboardcm");
  const query = await searchParams; const scope = await resolvePmPageScope(user, query); const serviceScope = { organizationId: scope.organization.id, plantId: scope.plant.id };
  const today = getBangkokDateString(); const selectedDate = validDate(query.date, today); const view = validView(query.view); const month = view === "day" ? `${selectedDate.slice(0, 7)}-01` : validMonth(query.month, `${today.slice(0, 7)}-01`); const canManage = canManagePmPlans(user);
  const [plans, groups] = await Promise.all([listPmCalendarPlans(user, serviceScope, month), canManage ? db.pmGroup.findMany({ where: { ...serviceScope, active: true }, select: { id: true, code: true, name: true }, orderBy: { code: "asc" } }) : Promise.resolve([])]);
  const selectedPlanId = plans.find(item => item.id === query.planId)?.id ?? plans.find(plan => plan.plannedDateKey === selectedDate)?.id; const plan = selectedPlanId ? await getPmPlanEditor(user, { ...serviceScope, planId: selectedPlanId }) : null; const preview = plan?.status === "DRAFT" ? await previewDraftPmPlan(user, { ...serviceScope, planId: plan.id }) : null;
  const confirmedAssets = canManage && plan?.status === "CONFIRMED" ? await db.asset.findMany({ where: { plantId: serviceScope.plantId, registrationStatus: "ACTIVE", pmWorks: { none: { pmPlanId: plan.id } } }, select: { id: true, code: true, nameTh: true }, orderBy: [{ code: "asc" }, { nameTh: "asc" }] }) : [];
  const scopeQuery = new URLSearchParams({ organizationId: scope.organization.id, plantId: scope.plant.id }).toString();
  return <AppShell><PmRouteShell title="PM Calendar" description={canManage ? "เลือกวันที่ แล้วเพิ่ม PM Group ได้มากกว่าหนึ่งกลุ่มใน Draft เดียว" : "ดูแผน PM ตาม Site ที่ได้รับสิทธิ์"} scope={scope} currentPage="calendar" canManageGroups={canManagePmGroups(user)} scopeAction="/dashboardpm" /><main className="mx-auto mt-5 grid max-w-6xl gap-5">
    {query.saved ? <p className="rounded-2xl bg-emerald-500/10 p-4 text-sm font-bold text-emerald-700" role="status">บันทึกแผน PM แล้ว</p> : null}{query.error ? <p className="rounded-2xl bg-red-500/10 p-4 text-sm font-bold text-red-700" role="alert">{query.error}</p> : null}
    <PmCalendarViewSwitcher view={view} monthHref={`/dashboardpm?${scopeQuery}&view=month&month=${month.slice(0, 7)}&date=${selectedDate}`} dayHref={`/dashboardpm?${scopeQuery}&view=day&month=${selectedDate.slice(0, 7)}&date=${selectedDate}${selectedPlanId ? `&planId=${selectedPlanId}` : ""}`} />
    <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="min-w-0">{view === "month" ? <PmCalendar canManage={canManage} month={month} plans={plans} scopeQuery={scopeQuery} /> : <PmDayColumn canManage={canManage} date={selectedDate} plan={plans.find(item => item.plannedDateKey === selectedDate)} scopeQuery={scopeQuery} today={today} />}</div>
      {plan && preview ? <PmPlanEditor actions={{ add: addGroup, remove: removeGroup, reschedule, deletePlan, confirm: confirmPlan }} calendarView={view} canManage={canManage} groups={groups} plan={plan} preview={preview} scope={serviceScope} /> : plan?.status === "CONFIRMED" && canManage ? <PmConfirmedPlanEditor actions={{ addAsset: addConfirmedAsset, reschedule: rescheduleConfirmed, cancel: cancelConfirmed }} assets={confirmedAssets} calendarView={view} plan={plan} scope={serviceScope} /> : plan ? <section className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow)]"><p className="text-sm font-bold text-[var(--primary)]">แผน PM</p><h2 className="mt-1 text-2xl font-extrabold">{plan.number ?? plan.plannedDateKey}</h2><p className="mt-3 text-sm text-[var(--muted)]">สถานะ {plan.status}</p></section> : canManage ? <section className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow)]"><p className="text-sm font-bold text-[var(--primary)]">วันที่เลือก</p><h2 className="mt-1 text-2xl font-extrabold">{selectedDate}</h2><p className="mt-3 text-sm text-[var(--muted)]">วันนี้ยังไม่มีแผน PM</p><form action={createPlan} className="mt-5"><AdminScopeHiddenFields scope={scope} /><input name="calendarView" type="hidden" value={view} /><input name="plannedDateKey" type="hidden" value={selectedDate} /><input name="submissionKey" type="hidden" value={randomUUID()} /><button className="min-h-12 w-full rounded-2xl bg-[var(--primary)] px-4 font-bold text-white">สร้าง Draft สำหรับวันนี้</button></form></section> : null}
    </div></main></AppShell>;
}
